# Generated by Django 4.1.2 on 2023-03-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('content', models.CharField(max_length=255, verbose_name='Контент')),
                ('status', models.CharField(max_length=255, verbose_name='Статус')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(verbose_name='Время обновления')),
                ('time_deadline', models.DateTimeField(verbose_name='Срок задачи')),
                ('overdue', models.BooleanField(default=False, verbose_name='Просрочена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
            },
        ),
    ]
