# Generated by Django 4.1.2 on 2022-12-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(max_length=255, verbose_name='Статус'),
        ),
    ]
