# Generated by Django 4.1.2 on 2022-12-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='time_create',
            field=models.DateTimeField(verbose_name='Время создания'),
        ),
    ]
