# Generated by Django 4.1.2 on 2022-12-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0003_alter_complaint_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
    ]
