# Generated by Django 4.1.2 on 2022-12-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_alter_complaint_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='time_update',
            field=models.DateTimeField(verbose_name='Время обновления'),
        ),
    ]
