# Generated by Django 4.1.2 on 2022-12-14 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0005_alter_complaint_time_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'verbose_name': 'Жалоба', 'verbose_name_plural': 'Жалобы'},
        ),
    ]
