# Generated by Django 4.1.2 on 2023-02-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='measurer',
            field=models.BooleanField(default=True, verbose_name='Статус замерщика'),
        ),
    ]
