# Generated by Django 4.1.2 on 2023-01-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_measurer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='measurer',
            field=models.BooleanField(default=True, verbose_name='Статус замерщика'),
        ),
    ]
