# Generated by Django 4.1.2 on 2023-02-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miscalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=255)),
                ('created_time', models.DateTimeField(blank=True)),
                ('last_update_time', models.DateTimeField(blank=True)),
                ('sum', models.FloatField(default=0.0, max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('offer', models.BooleanField(blank=True, max_length=255)),
                ('constructors', models.ManyToManyField(blank=True, to='calculation.constructor', verbose_name='Просчеты конструкторов')),
            ],
            options={
                'verbose_name': 'Просчет',
                'verbose_name_plural': 'Просчеты',
            },
        ),
    ]
