# Generated by Django 4.1.2 on 2023-06-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscalculation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscalculation',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='miscalculation',
            name='created_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='miscalculation',
            name='last_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='miscalculation',
            name='offer',
            field=models.BooleanField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='miscalculation',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
