# Generated by Django 4.1.2 on 2023-06-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscalculation', '0002_alter_miscalculation_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miscalculation',
            options={'verbose_name': 'Просчет полные', 'verbose_name_plural': 'Просчеты полные'},
        ),
    ]
