# Generated by Django 4.1.2 on 2023-06-15 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscalculation', '0003_alter_miscalculation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='commercial_offers/', verbose_name='Ком. предложения')),
                ('miscalculation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miscalculation.miscalculation', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Коммерческое предложение',
                'verbose_name_plural': 'Коммерческие предложения',
            },
        ),
    ]
