# Generated by Django 4.1.2 on 2022-12-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('call', '0001_initial'),
        ('miscalculation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('category_select', models.IntegerField(blank=True, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('addresses', models.ManyToManyField(blank=True, to='client.address')),
                ('calls', models.ManyToManyField(blank=True, to='call.call')),
                ('miscalculation', models.ManyToManyField(blank=True, to='miscalculation.miscalculation', verbose_name='Просчеты')),
                ('numbers', models.ManyToManyField(blank=True, to='client.number')),
            ],
        ),
    ]
