# Generated by Django 3.2 on 2022-10-04 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='number',
            new_name='numbers',
        ),
    ]
