# Generated by Django 4.1.2 on 2023-01-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscalculation', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='miscalculation',
            field=models.ManyToManyField(blank=True, to='miscalculation.miscalculation', verbose_name='Просчеты'),
        ),
        migrations.AddField(
            model_name='client',
            name='numbers',
            field=models.ManyToManyField(blank=True, to='client.number'),
        ),
        migrations.AddField(
            model_name='client',
            name='prompter',
            field=models.ManyToManyField(blank=True, to='client.prompter'),
        ),
    ]
