# Generated by Django 4.1.2 on 2022-12-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='complaints',
            field=models.ManyToManyField(blank=True, to='complaint.complaint', verbose_name='Жалобы'),
        ),
    ]
