# Generated by Django 4.1 on 2022-08-30 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name_client',
            new_name='name',
        ),
    ]
