# Generated by Django 4.1.2 on 2022-10-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
