# Generated by Django 4.1.2 on 2023-02-02 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompter',
            name='built_from',
        ),
    ]
