# Generated by Django 4.1 on 2022-08-30 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_name_client_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
