# Generated by Django 4.1.2 on 2023-02-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_miscalculation_client_numbers_client_prompter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompter',
            name='built_from',
        ),
        migrations.AddField(
            model_name='prompter',
            name='address',
            field=models.CharField(blank=True, default=False, max_length=255, verbose_name=''),
        ),
        migrations.AddField(
            model_name='prompter',
            name='built_from_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Из чего построен'),
        ),
        migrations.AddField(
            model_name='prompter',
            name='floor',
            field=models.CharField(blank=True, default=False, max_length=255, verbose_name='Комнаты'),
        ),
        migrations.AddField(
            model_name='prompter',
            name='layout',
            field=models.CharField(blank=True, default=False, max_length=255, verbose_name=''),
        ),
        migrations.AddField(
            model_name='prompter',
            name='reason_window_change',
            field=models.CharField(blank=True, default=False, max_length=255, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='prompter',
            name='installation_room',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комната установки'),
        ),
        migrations.AlterField(
            model_name='prompter',
            name='mounting_all',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Монтаж отливов/подоконников'),
        ),
        migrations.AlterField(
            model_name='prompter',
            name='winter_cold',
            field=models.CharField(blank=True, default=False, max_length=255, verbose_name='Зимой холодно'),
        ),
    ]
