# Generated by Django 4.1.2 on 2022-11-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscalculation', '0001_initial'),
        ('client', '0002_number_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='misculations',
            field=models.ManyToManyField(blank=True, to='miscalculation.miscalculation', verbose_name='Просчеты'),
        ),
    ]
