# Generated by Django 4.1.2 on 2023-06-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscalculation', '0003_alter_miscalculation_options'),
        ('client', '0003_remove_client_miscalculation_client_constructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='constructor',
        ),
        migrations.AddField(
            model_name='client',
            name='miscalculation',
            field=models.ManyToManyField(blank=True, to='miscalculation.miscalculation', verbose_name='Просчеты конструкторов'),
        ),
    ]
