# Generated by Django 4.1.2 on 2022-11-24 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_misculations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='time_create',
            new_name='time_created',
        ),
    ]
