# Generated by Django 4.1.2 on 2022-11-24 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_rename_time_create_client_time_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='misculations',
            new_name='miscalculations',
        ),
    ]
