# Generated by Django 3.2 on 2022-09-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20220923_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='number',
        ),
        migrations.AddField(
            model_name='client',
            name='number',
            field=models.ManyToManyField(to='client.Number'),
        ),
    ]
