# Generated by Django 3.2 on 2022-10-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0003_remove_call_status'),
        ('client', '0004_rename_name_number_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='addresses',
            field=models.ManyToManyField(blank=True, to='client.Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='calls',
            field=models.ManyToManyField(blank=True, to='call.Call'),
        ),
        migrations.AlterField(
            model_name='client',
            name='numbers',
            field=models.ManyToManyField(blank=True, to='client.Number'),
        ),
    ]
