# Generated by Django 4.1.2 on 2022-11-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_rename_misculations_client_miscalculations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='miscalculations',
            new_name='miscalculation',
        ),
    ]
