# Generated by Django 3.2 on 2022-09-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20220927_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='number',
            field=models.ManyToManyField(blank=True, null=True, to='client.Number'),
        ),
    ]
