version: '3.8'
services:
  crm_api:
    container_name: window_crm_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - crm_db
  crm_db:
    container_name: window_crm_db
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: window_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306