# Generated by Django 4.1.2 on 2023-03-06 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('content', models.CharField(max_length=255, verbose_name='Контент')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now_add=True, verbose_name='Время обновления')),
                ('time_deadline', models.DateTimeField(verbose_name='Срок задачи')),
                ('overdue', models.BooleanField(default=False, verbose_name='Просрочена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client', verbose_name='Клиент')),
            ],
        ),
    ]
