# Generated by Django 3.2 on 2022-08-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_task_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_deadline',
            field=models.DateTimeField(),
        ),
    ]
