from django.contrib import admin
from .models import *


admin.site.register(ConnectionProfile)
admin.site.register(Article)
admin.site.register(ConnectionProfileName)
admin.site.register(ColorInside)
admin.site.register(ColorOutside)
admin.site.register(SealantOutside)
admin.site.register(SealantInside)
admin.site.register(SealantShtapik)
admin.site.register(Cylinder)
admin.site.register(ArticleAdditionalProfile)
admin.site.register(AdditionalProfile)
admin.site.register(ProductTypeDoor)
admin.site.register(Gorbylki)
admin.site.register(Handles)
# admin.site.register(TypeLamination)
# admin.site.register(TypeLamination2)
admin.site.register(SealInternal)
admin.site.register(SealOutside)
# admin.site.register(SealBasic)
admin.site.register(Opening)
admin.site.register(Lock)
admin.site.register(DoorHandles)
admin.site.register(DoorHinges)
# admin.site.register(Cylinder)
admin.site.register(DoorCloser)
admin.site.register(OpeningLimiter)
admin.site.register(Profile)
admin.site.register(Fittings)
admin.site.register(ProductType)
admin.site.register(Door)
admin.site.register(Lamination)
admin.site.register(Aggregate)
# admin.site.register(SealOutside)
# admin.site.register(SealInternal)
admin.site.register(TypeLamination)
admin.site.register(TypeLamination2)
admin.site.register(SealBasic)
admin.site.register(SealRebate)
admin.site.register(SealantColor)
admin.site.register(Shpros)
admin.site.register(Shtapik)
admin.site.register(Sash)
admin.site.register(LaminationOutside)
admin.site.register(LaminationInside)
admin.site.register(ProfileWeight)
admin.site.register(Note)
admin.site.register(SupplyValve)


# EXTRAWORKS
admin.site.register(ProductsInstall)
admin.site.register(PvcSlopes)
admin.site.register(FreePositions)

# EXTRAMATERIALS

# admin.site.register(FavoritePositions)

admin.site.register(Windowsill)

# admin.site.register(Visors)
# admin.site.register(Flashing)
# admin.site.register(FlashingMetal)
# admin.site.register(Platband)
# admin.site.register(ExtensionsToProfile60)
# admin.site.register(ExtensionsToProfile70)
# admin.site.register(BayWindowToProfile60)
# admin.site.register(BayWindowToProfile70)
# admin.site.register(Connector90g)
# admin.site.register(Accessories)
# admin.site.register(OtherComplectation)
# admin.site.register(Locks)
# admin.site.register(StraightConnectors)
admin.site.register(Works)
admin.site.register(Flashing)
admin.site.register(Visors)
admin.site.register(Casing)
admin.site.register(LowTides)
