# Generated by Django 4.1.2 on 2023-01-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='agreements_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='id изображения'),
        ),
    ]
