# Generated by Django 4.1.2 on 2023-01-16 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurer', '0002_alter_measurement_agreements_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='agreements_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='measurer.agreements', verbose_name='изображения'),
        ),
    ]
