# Generated by Django 4.1.2 on 2023-01-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurer', '0002_remove_measurement_agreements_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='time',
            field=models.TimeField(blank=True, verbose_name='Время замера'),
        ),
    ]
