# Generated by Django 4.1.2 on 2023-01-16 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurer', '0003_alter_measurement_agreements_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='agreements_id',
            new_name='agreements',
        ),
    ]
