# Generated by Django 4.1.2 on 2023-01-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurer', '0003_measurement_number_alter_measurement_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес замера'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='client',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Комментарий к замеру'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateField(auto_created=True, blank=True, verbose_name='Дата замера'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Номер клиента'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='status',
            field=models.CharField(blank=True, max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='time',
            field=models.CharField(blank=True, max_length=255, verbose_name='Время замера'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='time_updated',
            field=models.DateTimeField(blank=True, verbose_name='Время обновления'),
        ),
    ]
