# Generated by Django 4.1.2 on 2023-01-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurer', '0004_rename_agreements_id_measurement_agreements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='agreements',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Изображения'),
        ),
    ]
