# Generated by Django 4.1.2 on 2023-01-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurer', '0005_alter_measurement_agreements'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='provisional_amounts',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Предварительная сумма'),
        ),
    ]
