# Generated by Django 4.1.2 on 2023-01-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurer', '0005_alter_measurement_who_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='executor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='manager',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Менеджер'),
        ),
    ]
