# Generated by Django 4.1.2 on 2023-01-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurer', '0006_measurement_provisional_amounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='provisional_amounts',
            new_name='preliminary_amount',
        ),
        migrations.AddField(
            model_name='measurement',
            name='final_amounts',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Окончательная сумма'),
        ),
    ]
