# Generated by Django 4.1.2 on 2023-01-17 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurer', '0007_rename_provisional_amounts_measurement_preliminary_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='final_amounts',
            new_name='final_amount',
        ),
    ]
