# Generated by Django 4.1 on 2022-08-29 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Imię')),
                ('surname', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('street', models.CharField(blank=True, max_length=1000, verbose_name='Adres')),
                ('city', models.CharField(blank=True, max_length=250, verbose_name='Miasto')),
                ('country', models.CharField(blank=True, max_length=250, verbose_name='Kraj')),
                ('phone', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numer tel.')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('S', 'Sprzedaż'), ('M', 'Spotkanie'), ('B', 'Brak kontaktu'), ('I', 'Inne')], max_length=15, verbose_name='Rodzaj')),
                ('subject', models.CharField(max_length=100, verbose_name='Tytuł')),
                ('description', models.CharField(max_length=1000, verbose_name='Opis')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Zaplanowana data')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='klient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
            ],
        ),
    ]
