# Generated by Django 4.1.2 on 2023-02-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_call', models.CharField(blank=True, max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(blank=True)),
                ('call_status', models.CharField(blank=True, max_length=255)),
                ('call_type', models.CharField(blank=True, max_length=255)),
                ('client_id', models.IntegerField(blank=True)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('manager', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Call_Okna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_call', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
