# Generated by Django 4.1.2 on 2023-01-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='client_id',
            field=models.IntegerField(blank=True),
        ),
    ]
