# Generated by Django 3.2 on 2022-09-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='status',
            new_name='call_status',
        ),
        migrations.AddField(
            model_name='call',
            name='call_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
