# Generated by Django 4.1.2 on 2023-02-20 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('calls_table', '0006_delete_outgoingcalls'),
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Call_Okna',
            new_name='CallOkna',
        ),
        migrations.RenameModel(
            old_name='Call',
            new_name='CallWindow',
        ),
    ]
