# Generated by Django 4.1.2 on 2022-12-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='client_name',
        ),
        migrations.AlterField(
            model_name='call',
            name='client_id',
            field=models.IntegerField(blank=True, max_length=255),
        ),
    ]
