# Generated by Django 3.2 on 2022-09-06 09:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('call', '0002_call_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='date',
        ),
        migrations.RemoveField(
            model_name='call',
            name='time',
        ),
        migrations.AddField(
            model_name='call',
            name='comment',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='call',
            name='timestamp',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='call',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client'),
        ),
    ]
