# Generated by Django 3.2 on 2022-09-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0002_auto_20220914_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
