# Generated by Django 3.2 on 2022-10-07 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0002_auto_20221007_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='status',
        ),
    ]
