# Generated by Django 4.1.2 on 2023-02-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0002_rename_call_okna_callokna_rename_call_callwindow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callokna',
            name='id_call',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
