# Generated by Django 3.2 on 2022-09-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0003_auto_20220906_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='timestamp',
            new_name='datetime',
        ),
    ]
