# Generated by Django 4.1.2 on 2023-02-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0003_alter_callokna_id_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callwindow',
            name='call_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='callwindow',
            name='call_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='callwindow',
            name='client_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callwindow',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='callwindow',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callwindow',
            name='id_call',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='callwindow',
            name='manager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='callwindow',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
