# Generated by Django 3.2 on 2022-10-08 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0003_remove_call_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='name_client',
            new_name='client_name',
        ),
    ]
