# Generated by Django 3.2 on 2022-09-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0003_call_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='id_call',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
