# Generated by Django 3.2 on 2022-10-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0004_rename_name_client_call_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
