# Generated by Django 3.2 on 2022-09-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0004_alter_call_id_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='datetime',
            field=models.DateTimeField(blank=True),
        ),
    ]
