# Generated by Django 3.2 on 2022-09-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0004_rename_timestamp_call_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='to_phone',
        ),
        migrations.AlterField(
            model_name='call',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='call',
            name='manager',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
