# Generated by Django 3.2 on 2022-09-23 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0005_alter_call_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='id_client',
        ),
    ]
