# Generated by Django 3.2 on 2022-09-08 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0005_auto_20220908_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='from_phone',
            new_name='id_call',
        ),
        migrations.AddField(
            model_name='call',
            name='number',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='call',
            name='client',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='call',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
