# Generated by Django 4.1.2 on 2023-03-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurer_window', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sum_in_materials_in_byn',
            field=models.FloatField(default=0.0, verbose_name='Сумма материалов в BYN'),
        ),
        migrations.AddField(
            model_name='order',
            name='sum_in_materials_in_currency',
            field=models.FloatField(default=0.0, verbose_name='Сумма материалов в валюте'),
        ),
    ]
