# Generated by Django 4.1.2 on 2023-03-05 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('measurer_window', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowsill',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='windowsill',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена BYN'),
        ),
        migrations.AlterField(
            model_name='windowsill',
            name='price_in_currency',
            field=models.FloatField(blank=True, null=True, verbose_name=' Цена EUR/USD'),
        ),
        migrations.CreateModel(
            name='WindowsillCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(default=0.0, max_length=255, verbose_name='Ширина')),
                ('length', models.FloatField(default=0.0, max_length=255, verbose_name='Длинна')),
                ('count', models.FloatField(default=0.0, max_length=255, verbose_name='Количество')),
                ('square_meter', models.FloatField(default=0.0, max_length=255, verbose_name='В метрах квадратных')),
                ('linear_meter', models.FloatField(default=0.0, max_length=255, verbose_name='В метрах погонных')),
                ('price_output', models.FloatField(default=0.0, max_length=255, verbose_name='Цена')),
                ('windowsill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurer_window.windowsill', verbose_name='Подоконник')),
            ],
            options={
                'verbose_name': 'Просчет подоконника',
                'verbose_name_plural': 'Просчеты подоконников',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя заказчика')),
                ('date', models.DateField(verbose_name='Дата замера')),
                ('sum', models.FloatField(default=0.0, verbose_name='Сумма просчета')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[{1, 'шт'}, {2, 'м2'}], null=True, verbose_name='Статус')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
