# Generated by Django 4.1.2 on 2023-03-06 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('measurer_window', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.AddField(
            model_name='lowtidescalc',
            name='low_tides',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurer_window.lowtides', verbose_name='Отлив'),
        ),
        migrations.AddField(
            model_name='lowtidescomplectcalc',
            name='low_tides',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurer_window.lowtides', verbose_name='Комплектующие отлива'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Замерщик'),
        ),
        migrations.AddField(
            model_name='order',
            name='windowsill_calc',
            field=models.ManyToManyField(blank=True, to='measurer_window.windowsillcalc', verbose_name='Просчеты подоконников'),
        ),
        migrations.AlterField(
            model_name='windowsill',
            name='unit',
            field=models.PositiveSmallIntegerField(choices=[{1, 'м2'}, {2, 'шт'}], default=1, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurer_window.status', verbose_name='статус'),
        ),
    ]
