# Generated by Django 4.1.2 on 2023-03-06 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('measurer_window', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='windowsill_calc',
            field=models.ManyToManyField(blank=True, to='measurer_window.windowsillcalc', verbose_name='Просчеты подоконников'),
        ),
        migrations.AddField(
            model_name='lowtidescomplectcalc',
            name='low_tides',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurer_window.lowtides', verbose_name='Комплектующие отлива'),
        ),
        migrations.AddField(
            model_name='lowtidescalc',
            name='low_tides',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurer_window.lowtides', verbose_name='Отлив'),
        ),
    ]
