# Generated by Django 4.1.2 on 2023-03-06 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurer_window', '0002_status_unit_windowsillwidth_lowtidescalc_low_tides_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowsillcalc',
            name='width',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurer_window.windowsillwidth', verbose_name='Полка подоконник'),
        ),
    ]
