# Generated by Django 4.1.2 on 2023-03-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurer_window', '0002_alter_windowsill_name_alter_windowsill_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Замер', 'verbose_name_plural': 'Замеры'},
        ),
        migrations.AddField(
            model_name='order',
            name='sum_in_currency',
            field=models.FloatField(default=0.0, verbose_name='Сумма просчета в EUR/USD'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[{1, 'Заключен договор'}, {2, 'Отказ после замера'}, {'Придет на офис', 3}], null=True, verbose_name='Статус'),
        ),
    ]
