# Generated by Django 4.1.2 on 2023-03-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurer_window', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowsill',
            name='unit',
            field=models.PositiveSmallIntegerField(choices=[{1, 'м2'}, {2, 'шт'}], default=1, verbose_name='Единица измерения'),
        ),
    ]
