# Generated by Django 4.1.2 on 2023-03-06 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurer_window', '0003_alter_windowsillcalc_width'),
    ]

    operations = [
        migrations.RenameField(
            model_name='windowsillcalc',
            old_name='width',
            new_name='windowsill_width',
        ),
    ]
