# Generated by Django 4.1.2 on 2023-03-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurer_window', '0003_alter_order_options_order_sum_in_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона'),
        ),
    ]
