# Generated by Django 4.1.2 on 2023-03-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurer_window', '0005_order_windowsill_calc'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowsillcalc',
            name='order_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='windowsill_calc',
            field=models.ManyToManyField(blank=True, null=True, to='measurer_window.windowsillcalc', verbose_name='Просчеты подоконников'),
        ),
    ]
