# Generated by Django 4.1.2 on 2023-03-08 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurer_window', '0005_works_workscalc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workscalc',
            name='mounting_materials',
        ),
        migrations.AddField(
            model_name='workscalc',
            name='works',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurer_window.works', verbose_name='Работа'),
        ),
    ]
