# Generated by Django 4.1.2 on 2023-03-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurer_window', '0006_windowsillcalc_order_id_alter_order_windowsill_calc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowsillcalc',
            name='count',
            field=models.IntegerField(default=0.0, max_length=255, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='windowsillcalc',
            name='length',
            field=models.IntegerField(default=0.0, max_length=255, verbose_name='Длинна'),
        ),
        migrations.AlterField(
            model_name='windowsillcalc',
            name='order_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер замера'),
        ),
        migrations.AlterField(
            model_name='windowsillcalc',
            name='width',
            field=models.IntegerField(default=0.0, max_length=255, verbose_name='Ширина'),
        ),
    ]
