# Generated by Django 4.1.2 on 2023-03-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurer_window', '0006_remove_workscalc_mounting_materials_workscalc_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sum_works_byn',
            field=models.FloatField(default=0.0, verbose_name='Сумма работ в BYN'),
        ),
        migrations.AddField(
            model_name='order',
            name='sum_works_currency',
            field=models.FloatField(default=0.0, verbose_name='Сумма работ в валюте'),
        ),
    ]
