# Generated by Django 4.1.2 on 2023-03-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurer_window', '0007_alter_windowsillcalc_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windowsillcalc',
            name='price_output',
        ),
        migrations.AddField(
            model_name='windowsillcalc',
            name='price_byn',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='Цена BYN'),
        ),
        migrations.AddField(
            model_name='windowsillcalc',
            name='price_currency',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='Цена EUR/USD'),
        ),
    ]
