# Generated by Django 4.1.2 on 2023-03-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurer_window', '0008_windowsillcolor_windowsillcalc_windowsill_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowsillConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('price_in_currency', models.FloatField(blank=True, null=True, verbose_name=' Цена EUR/USD')),
                ('price_in_byn', models.FloatField(blank=True, null=True, verbose_name='Цена BYN')),
            ],
            options={
                'verbose_name': 'Соединитель подоконника',
                'verbose_name_plural': 'Соединители подоконников',
            },
        ),
        migrations.CreateModel(
            name='WindowsillPlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('price_in_currency', models.FloatField(blank=True, null=True, verbose_name=' Цена EUR/USD')),
                ('price_in_byn', models.FloatField(blank=True, null=True, verbose_name='Цена BYN')),
            ],
            options={
                'verbose_name': 'Заглушка подоконника',
                'verbose_name_plural': 'Заглушки подоконников',
            },
        ),
        migrations.AddField(
            model_name='windowsillcalc',
            name='windowsill_connection_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество соединителей'),
        ),
        migrations.AddField(
            model_name='windowsillcalc',
            name='windowsill_plug_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество заглушек'),
        ),
        migrations.AddField(
            model_name='windowsillcalc',
            name='windowsill_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurer_window.windowsillconnection', verbose_name='Соединитель подоконника'),
        ),
        migrations.AddField(
            model_name='windowsillcalc',
            name='windowsill_plug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurer_window.windowsillplug', verbose_name='Заглушка подоконника'),
        ),
    ]
