# Generated by Django 4.1.2 on 2023-03-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurer_window', '0009_rename_price_windowsill_price_in_byn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowsillcalc',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='windowsillcalc',
            name='length',
            field=models.IntegerField(default=0, verbose_name='Длинна'),
        ),
        migrations.AlterField(
            model_name='windowsillcalc',
            name='width',
            field=models.IntegerField(default=0, verbose_name='Ширина'),
        ),
    ]
