# Generated by Django 4.1.2 on 2023-03-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurer_window', '0010_alter_windowsillcalc_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='windowsill_calc',
            field=models.ManyToManyField(blank=True, to='measurer_window.windowsillcalc', verbose_name='Просчеты подоконников'),
        ),
    ]
