# Generated by Django 4.1.2 on 2023-03-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurer_window', '0010_remove_windowsillcalc_price_in_byn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windowsillcalc',
            name='count',
        ),
        migrations.AddField(
            model_name='windowsillcalc',
            name='windowsill_count',
            field=models.IntegerField(default=0, verbose_name='Количество  подоконников'),
        ),
    ]
