# Generated by Django 4.1.2 on 2023-03-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurer_window', '0011_alter_order_windowsill_calc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sum',
        ),
        migrations.AddField(
            model_name='order',
            name='sum_in_byn',
            field=models.FloatField(default=0.0, verbose_name='Сумма просчета BYN'),
        ),
    ]
