# Generated by Django 4.1.2 on 2023-03-12 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurer_window', '0011_remove_windowsillcalc_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowTidesColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цвет подоконника')),
            ],
            options={
                'verbose_name': 'Цвет подоконника',
                'verbose_name_plural': 'Цвета подоконников',
            },
        ),
        migrations.CreateModel(
            name='LowTidesConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('price_in_currency', models.FloatField(blank=True, null=True, verbose_name=' Цена EUR/USD')),
                ('price_in_byn', models.FloatField(blank=True, null=True, verbose_name='Цена BYN')),
            ],
            options={
                'verbose_name': 'Соединитель отлива',
                'verbose_name_plural': 'Соединители отливов',
            },
        ),
        migrations.CreateModel(
            name='LowTidesPlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('price_in_currency', models.FloatField(blank=True, null=True, verbose_name=' Цена EUR/USD')),
                ('price_in_byn', models.FloatField(blank=True, null=True, verbose_name='Цена BYN')),
            ],
            options={
                'verbose_name': 'Заглушка отлива',
                'verbose_name_plural': 'Заглушки отливов',
            },
        ),
        migrations.RemoveField(
            model_name='lowtidescalc',
            name='count',
        ),
        migrations.RemoveField(
            model_name='lowtidescalc',
            name='price_in_byn',
        ),
        migrations.RemoveField(
            model_name='lowtidescalc',
            name='price_in_currency',
        ),
        migrations.RemoveField(
            model_name='lowtidescalc',
            name='width',
        ),
        migrations.AddField(
            model_name='lowtidescalc',
            name='low_tides_connection_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество соединителей'),
        ),
        migrations.AddField(
            model_name='lowtidescalc',
            name='low_tides_count',
            field=models.IntegerField(default=0, verbose_name='Количество  подоконников'),
        ),
        migrations.AddField(
            model_name='lowtidescalc',
            name='low_tides_plug_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество заглушек'),
        ),
        migrations.AddField(
            model_name='lowtidescalc',
            name='low_tides_width',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ширина'),
        ),
        migrations.AddField(
            model_name='lowtidescalc',
            name='sum_connection_byn',
            field=models.FloatField(blank=True, default=0.0, max_length=255, null=True, verbose_name='Цена соединитеей в BYN'),
        ),
        migrations.AddField(
            model_name='lowtidescalc',
            name='sum_connection_currency',
            field=models.FloatField(blank=True, default=0.0, max_length=255, null=True, verbose_name='Цена соединителей в EUR/USD'),
        ),
        migrations.AddField(
            model_name='lowtidescalc',
            name='sum_in_byn',
            field=models.FloatField(blank=True, default=0.0, max_length=255, null=True, verbose_name='Цена BYN'),
        ),
        migrations.AddField(
            model_name='lowtidescalc',
            name='sum_in_currency',
            field=models.FloatField(blank=True, default=0.0, max_length=255, null=True, verbose_name='Цена EUR/USD'),
        ),
        migrations.AddField(
            model_name='lowtidescalc',
            name='sum_low_tides_byn',
            field=models.FloatField(blank=True, default=0.0, max_length=255, null=True, verbose_name='Цена подоконника в BYN'),
        ),
        migrations.AddField(
            model_name='lowtidescalc',
            name='sum_low_tides_currency',
            field=models.FloatField(blank=True, default=0.0, max_length=255, null=True, verbose_name='Цена подоконника в EUR/USD'),
        ),
        migrations.AddField(
            model_name='lowtidescalc',
            name='sum_plug_byn',
            field=models.FloatField(blank=True, default=0.0, max_length=255, null=True, verbose_name='Цена заглушек в BYN'),
        ),
        migrations.AddField(
            model_name='lowtidescalc',
            name='sum_plug_currency',
            field=models.FloatField(blank=True, default=0.0, max_length=255, null=True, verbose_name='Цена заглушек в EUR/USD'),
        ),
        migrations.AlterField(
            model_name='lowtidescalc',
            name='linear_meter',
            field=models.FloatField(blank=True, default=0.0, max_length=255, null=True, verbose_name='В метрах погонных'),
        ),
        migrations.AlterField(
            model_name='lowtidescalc',
            name='square_meter',
            field=models.FloatField(blank=True, default=0.0, max_length=255, null=True, verbose_name='В метрах квадратных'),
        ),
        migrations.DeleteModel(
            name='WindowsillComplectCalc',
        ),
        migrations.AddField(
            model_name='lowtidescalc',
            name='low_tides_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurer_window.lowtidescolor', verbose_name='Цвет отлива'),
        ),
        migrations.AddField(
            model_name='lowtidescalc',
            name='low_tides_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurer_window.lowtidesconnection', verbose_name='Соединитель подоконника'),
        ),
        migrations.AddField(
            model_name='lowtidescalc',
            name='low_tides_plug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurer_window.lowtidesplug', verbose_name='Заглушка отлива'),
        ),
    ]
