# Generated by Django 4.1.2 on 2023-03-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurer_window', '0012_remove_order_sum_order_sum_in_byn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[{0, 'Активная заявка'}, {'Договор заключен', 1}, {2, 'Думает'}, {3, 'Придет на офис'}, {'Банковская рассрочка', 4}, {'Отказ до замера', 5}, {'Отказ после замера', 6}], default=0, null=True, verbose_name='Статус'),
        ),
    ]
