# Generated by Django 4.1.2 on 2023-03-12 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurer_window', '0012_lowtidescolor_lowtidesconnection_lowtidesplug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowTidesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Отлив',
                'verbose_name_plural': 'Отливы',
            },
        ),
        migrations.AlterField(
            model_name='lowtidescalc',
            name='low_tides_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurer_window.lowtidesconnection', verbose_name='Соединитель отлива'),
        ),
        migrations.AddField(
            model_name='lowtidescalc',
            name='low_tides_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurer_window.lowtidestype', verbose_name='Тип отлива'),
        ),
    ]
