# Generated by Django 4.1.2 on 2023-03-06 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurer_window', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowsill',
            name='unit',
            field=models.PositiveSmallIntegerField(choices=[{'м2', 1}, {2, 'шт'}], verbose_name='Единица измерения'),
        ),
        migrations.CreateModel(
            name='WindowsillComplectCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, null=True, verbose_name='Номер замера')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('price_in_byn', models.FloatField(default=0.0, max_length=255, verbose_name='Цена BYN')),
                ('price_in_currency', models.FloatField(default=0.0, max_length=255, verbose_name='Цена EUR/USD')),
                ('windowsill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurer_window.windowsill', verbose_name='Подоконник')),
            ],
            options={
                'verbose_name': 'Просчет комплектующих подоконников',
                'verbose_name_plural': 'Просчеты комплектующих подоконника',
            },
        ),
    ]
