# Generated by Django 4.1.2 on 2023-03-06 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurer_window', '0014_alter_windowsill_unit_windowsillcomplectcalc'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowTides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('price_in_currency', models.FloatField(blank=True, null=True, verbose_name=' Цена EUR/USD')),
                ('price_in_byn', models.FloatField(blank=True, null=True, verbose_name='Цена BYN')),
                ('unit', models.PositiveSmallIntegerField(choices=[{1, 'м2'}, {2, 'шт'}], verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Отлив',
                'verbose_name_plural': 'Отливы',
            },
        ),
        migrations.AlterField(
            model_name='windowsillcomplectcalc',
            name='windowsill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurer_window.windowsill', verbose_name='Комплектующие подоконника'),
        ),
        migrations.CreateModel(
            name='LowTidesComplectCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, null=True, verbose_name='Номер замера')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('price_in_byn', models.FloatField(default=0.0, max_length=255, verbose_name='Цена BYN')),
                ('price_in_currency', models.FloatField(default=0.0, max_length=255, verbose_name='Цена EUR/USD')),
                ('low_tides', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurer_window.lowtides', verbose_name='Комплектующие отлива')),
            ],
            options={
                'verbose_name': 'Просчет комплектующих отливов',
                'verbose_name_plural': 'Просчеты комплектующих отливов',
            },
        ),
        migrations.CreateModel(
            name='LowTidesCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, null=True, verbose_name='Номер замера')),
                ('width', models.IntegerField(default=0, verbose_name='Ширина')),
                ('length', models.IntegerField(default=0, verbose_name='Длинна')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('square_meter', models.FloatField(default=0.0, max_length=255, verbose_name='В метрах квадратных')),
                ('linear_meter', models.FloatField(default=0.0, max_length=255, verbose_name='В метрах погонных')),
                ('price_in_byn', models.FloatField(default=0.0, max_length=255, verbose_name='Цена BYN')),
                ('price_in_currency', models.FloatField(default=0.0, max_length=255, verbose_name='Цена EUR/USD')),
                ('low_tides', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurer_window.lowtides', verbose_name='Отлив')),
            ],
            options={
                'verbose_name': 'Просчет отлива',
                'verbose_name_plural': 'Просчеты отливов',
            },
        ),
    ]
