# Generated by Django 4.2 on 2023-04-25 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurer_window', '0015_filling_fittings_profile_windowscalc'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowDiscountMarkups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField(default=0.0, max_length=255, verbose_name='Значение')),
                ('markup', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка диллерская')),
                ('in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах')),
                ('fittings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='measurer_window.fittings', verbose_name='Фурнитура')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='measurer_window.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Скидка/Наценка на окно',
                'verbose_name_plural': 'Скидки/Наценки на окна',
            },
        ),
    ]
