# Generated by Django 4.1.2 on 2022-12-19 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constructor', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('value', models.FloatField(default=0.0, max_length=255, verbose_name='Значение')),
                ('auto', models.BooleanField(default=True, verbose_name='Получать автоматически')),
                ('add_percent', models.BooleanField(default=False, verbose_name='Добавлять в процентах')),
                ('value_percent', models.FloatField(default=0.0, max_length=255, verbose_name='Значение в процентах')),
            ],
            options={
                'verbose_name': 'Курс валют',
                'verbose_name_plural': 'Курсы валют',
            },
        ),
        migrations.CreateModel(
            name='LowTidesCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_tides_id', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='№ Отлив')),
                ('markups_type', models.CharField(max_length=255, verbose_name='Наценка ')),
                ('width', models.FloatField(default=0.0, max_length=255, verbose_name='Ширина')),
                ('length', models.FloatField(default=0.0, max_length=255, verbose_name='Длинна')),
                ('count', models.FloatField(default=0.0, max_length=255, verbose_name='количество')),
                ('price_output', models.FloatField(default=0.0, max_length=255, verbose_name='цена')),
            ],
            options={
                'verbose_name': 'Просчет отлива',
                'verbose_name_plural': 'Просчеты отливов',
            },
        ),
        migrations.CreateModel(
            name='Markups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_tides', models.FloatField(default=0.0, max_length=255, verbose_name='Отливы ')),
                ('low_tides_in_percent', models.BooleanField(default=True, verbose_name='считать в процентах отливы')),
                ('window', models.FloatField(default=0.0, max_length=255, verbose_name='Окна')),
                ('window_in_percent', models.BooleanField(default=True, verbose_name='считать в процентах окно')),
            ],
            options={
                'verbose_name': 'Наценки',
                'verbose_name_plural': 'Наценки',
            },
        ),
        migrations.CreateModel(
            name='WindowsCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Скидка на окно')),
                ('profile_id', models.IntegerField(blank=True, null=True, verbose_name='Профиль id')),
                ('fittings_id', models.IntegerField(blank=True, null=True, verbose_name='Фурнитура id ')),
                ('currency_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта имя')),
                ('currency_value', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Валюта значение НБРБ')),
                ('price_input', models.FloatField(default=0.0, max_length=255, verbose_name='Входная цена')),
                ('price_output', models.FloatField(default=0.0, max_length=255, verbose_name='Выходная цена ( с наценкой )')),
                ('markup_value', models.FloatField(default=0.0, max_length=255, verbose_name='Значение наценки')),
                ('markup_percent', models.BooleanField(default=True, verbose_name='Наценка в процентах')),
            ],
            options={
                'verbose_name': 'Просчет окна',
                'verbose_name_plural': 'Просчеты окон',
            },
        ),
        migrations.CreateModel(
            name='WindowsillCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windowsill_id', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='№ Подоконник')),
                ('markups_type', models.CharField(max_length=255, verbose_name='Наценка ')),
                ('width', models.FloatField(default=0.0, max_length=255, verbose_name='ширина')),
                ('length', models.FloatField(default=0.0, max_length=255, verbose_name='длинна')),
                ('count', models.FloatField(default=0.0, max_length=255, verbose_name='количество')),
                ('price_output', models.FloatField(default=0.0, max_length=255, verbose_name='цена')),
            ],
            options={
                'verbose_name': 'Просчет подоконника',
                'verbose_name_plural': 'Просчеты подоконников',
            },
        ),
        migrations.CreateModel(
            name='Windowsill_Markups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markups_diler', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка диллерская')),
                ('markups_diler_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( диллер )')),
                ('markups_retail', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка розничная')),
                ('markups_retail_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( розница )')),
                ('windowsill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.windowsill', verbose_name='Подоконник')),
            ],
            options={
                'verbose_name': 'Наценка на подоконник',
                'verbose_name_plural': 'Наценка на подоконники',
            },
        ),
        migrations.CreateModel(
            name='WindowDiscountMarkups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField(default=0.0, max_length=255, verbose_name='Значение')),
                ('markups', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка')),
                ('markups_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах')),
                ('fittings_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.fittings', verbose_name='Фурнитура')),
                ('profile_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Скидка/Наценка на окно',
                'verbose_name_plural': 'Скидки/Наценки на окна',
            },
        ),
        migrations.CreateModel(
            name='LowTides_Markups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markups_diler', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка диллерская')),
                ('markups_diler_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( диллер )')),
                ('markups_retail', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка розничная')),
                ('markups_retail_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( розница )')),
                ('lowtides', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.lowtides', verbose_name='Отливы')),
            ],
            options={
                'verbose_name': 'Наценка на отлив',
                'verbose_name_plural': 'Наценка на отливы',
            },
        ),
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('price_input', models.FloatField(blank=True, default=0.0, max_length=255, null=True, verbose_name='Входная цена')),
                ('price_window', models.FloatField(blank=True, default=0.0, max_length=255, null=True, verbose_name='Цена окно ( с наценкой )')),
                ('price_material', models.FloatField(blank=True, default=0.0, max_length=255, null=True, verbose_name='Цена материалов ( с наценкой )')),
                ('price_constructor', models.FloatField(blank=True, default=0.0, max_length=255, null=True, verbose_name='Цена всего просчета')),
                ('accessories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.accessories', verbose_name='Комлпектующие')),
                ('aggregate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.aggregate', verbose_name='Заполнитель №1')),
                ('bay_window_to_profile60', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.baywindowtoprofile60', verbose_name='Эркер к профилю 60мм')),
                ('bay_window_to_profile70', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.baywindowtoprofile70', verbose_name='Эркер к профилю 70мм')),
                ('connector_90g', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.connector90g', verbose_name='Соединитель 90гр')),
                ('extensions_to_profile60', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.extensionstoprofile60', verbose_name='Доборы к профилю 60мм')),
                ('extensions_to_profile70', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.extensionstoprofile70', verbose_name='Доборы к профилю 70мм')),
                ('favorite_positions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.favoritepositions', verbose_name='Избранные позиции')),
                ('flashing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.flashing', verbose_name='Нащельник')),
                ('flashing_metal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.flashingmetal', verbose_name='Нащельник Металл')),
                ('free_positions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.freepositions', verbose_name='Бесплатные позиции')),
                ('handles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.handles', verbose_name='Ручка')),
                ('lamination_inside', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.laminationinside', verbose_name='Ланиманция внутри')),
                ('lamination_outside', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.laminationoutside', verbose_name='Ламинация снаружи')),
                ('locks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.locks', verbose_name='Замок')),
                ('lowtides_calc', models.ManyToManyField(blank=True, to='calculation.lowtidescalc', verbose_name='Просчеты отливов')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.note', verbose_name='Примечание')),
                ('platband', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.platband', verbose_name='Наличник')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.producttype', verbose_name='Тип изделия')),
                ('products_install', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.productsinstall', verbose_name='Монтаж изделий')),
                ('profile_weight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.profileweight', verbose_name='Масса профиля')),
                ('pvc_slopes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.pvcslopes', verbose_name='Откосы ПВХ')),
                ('sash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sash', verbose_name='Створка')),
                ('seal_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealcolor', verbose_name='Цвет уплотнения')),
                ('seal_internal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealinternal', verbose_name='Уплотнение внутренее')),
                ('seal_outside', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealoutside', verbose_name='Уплотнение снаружи')),
                ('seal_rebate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealrebate', verbose_name='Уплотнение притвора')),
                ('shpros', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.shpros', verbose_name='Шпрос')),
                ('shtapik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.shtapik', verbose_name='Шталик')),
                ('straight_connectors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.straightconnectors', verbose_name='Прямые соединители')),
                ('supply_valve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.supplyvalve', verbose_name='Приточный клапан')),
                ('visors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.visors', verbose_name='Козырьки')),
                ('window_calc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculation.windowscalc', verbose_name='Просчет окна')),
                ('windowsills_calc', models.ManyToManyField(blank=True, to='calculation.windowsillcalc', verbose_name='Просчеты подоконников')),
                ('works', models.ManyToManyField(blank=True, to='constructor.works', verbose_name='Работы')),
            ],
            options={
                'verbose_name': 'Просчет конструктора',
                'verbose_name_plural': 'Просчеты конструкторов',
            },
        ),
    ]
