# Generated by Django 4.1.2 on 2022-10-15 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constructor', '0004_remove_windowsill_price_windowsill_price_input_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.FloatField(default=0.0, max_length=255)),
            ],
            options={
                'verbose_name': 'Курс валют',
                'verbose_name_plural': 'Курсы валют',
            },
        ),
        migrations.CreateModel(
            name='WindowsillCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(default=0.0, max_length=255)),
                ('length', models.FloatField(default=0.0, max_length=255)),
                ('count', models.FloatField(default=0.0, max_length=255)),
                ('price', models.FloatField(default=0.0, max_length=255)),
                ('windowsill_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.windowsill', verbose_name='Подоконник')),
            ],
        ),
        migrations.CreateModel(
            name='WindowDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField(default=0.0, max_length=255)),
                ('fitting_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.fittings', verbose_name='Фурнитура')),
                ('profile_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Скидка на окно',
                'verbose_name_plural': 'Скидки на окна',
            },
        ),
    ]
