# Generated by Django 4.1.2 on 2023-02-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructor',
            name='additional_profile',
        ),
        migrations.RemoveField(
            model_name='constructor',
            name='aggregate',
        ),
        migrations.RemoveField(
            model_name='constructor',
            name='connection_profile',
        ),
        migrations.RemoveField(
            model_name='constructor',
            name='door',
        ),
        migrations.RemoveField(
            model_name='constructor',
            name='gorbylki',
        ),
        migrations.RemoveField(
            model_name='constructor',
            name='handles',
        ),
        migrations.RemoveField(
            model_name='constructor',
            name='lamination',
        ),
        migrations.RemoveField(
            model_name='constructor',
            name='lowtides_calc',
        ),
        migrations.RemoveField(
            model_name='constructor',
            name='other_complectation',
        ),
        migrations.RemoveField(
            model_name='constructor',
            name='price_constructor',
        ),
        migrations.RemoveField(
            model_name='constructor',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='constructor',
            name='sash',
        ),
        migrations.RemoveField(
            model_name='constructor',
            name='sealant',
        ),
        migrations.RemoveField(
            model_name='constructor',
            name='shtapik',
        ),
        migrations.RemoveField(
            model_name='constructor',
            name='window_calc',
        ),
        migrations.RemoveField(
            model_name='constructor',
            name='windowsills_calc',
        ),
        migrations.RemoveField(
            model_name='constructor',
            name='works',
        ),
    ]
