# Generated by Django 4.1.2 on 2023-02-08 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0003_alter_profile_options'),
        ('calculation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works_Markups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markup', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка на работу')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.works', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Наценка на подоконник',
                'verbose_name_plural': 'Наценка на подоконники',
            },
        ),
    ]
