# Generated by Django 4.2 on 2023-05-08 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructor',
            old_name='sploes_of_metal_calc',
            new_name='slopes_of_metal_calc',
        ),
    ]
