# Generated by Django 4.1.2 on 2023-02-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visors_markups',
            options={'verbose_name': 'Наценка на козырек', 'verbose_name_plural': 'Наценка на козырьки'},
        ),
        migrations.AddField(
            model_name='flashingcalc',
            name='square_meter',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='В метрах квадратных'),
        ),
    ]
