# Generated by Django 4.1.2 on 2022-10-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='windowsillcalc',
            old_name='price',
            new_name='price_output',
        ),
    ]
