# Generated by Django 4.1.2 on 2023-01-19 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0003_gorbylki'),
        ('calculation', '0002_remove_constructor_accessories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructor',
            name='gorbylki',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.gorbylki', verbose_name='Горбыльки'),
        ),
        migrations.AlterField(
            model_name='constructor',
            name='handles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.handles', verbose_name='Ручки'),
        ),
        migrations.AlterField(
            model_name='constructor',
            name='sash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sash', verbose_name='Створка'),
        ),
        migrations.AlterField(
            model_name='constructor',
            name='shtapik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.shtapik', verbose_name='Штапик'),
        ),
    ]
