# Generated by Django 4.1.2 on 2023-02-07 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_casing_provider_flashing_provider_lowtides_provider_and_more'),
        ('calculation', '0002_remove_constructor_additional_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='additional_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.additionalprofile', verbose_name='Доборные профиля'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='aggregate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.aggregate', verbose_name='Заполнитель'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='casing_calc',
            field=models.ManyToManyField(blank=True, to='calculation.casingcalc', verbose_name='Просчеты козырьков'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='connection_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.connectionprofile', verbose_name='Соединительные профиля'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='door',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.door', verbose_name='Двери'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='flashing_calc',
            field=models.ManyToManyField(blank=True, to='calculation.flashingcalc', verbose_name='Просчеты нащельников'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='gorbylki',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.gorbylki', verbose_name='Горбыльки'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='handles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.handles', verbose_name='Ручки'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='lamination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.lamination', verbose_name='Ламинация'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='lowtides_calc',
            field=models.ManyToManyField(blank=True, to='calculation.lowtidescalc', verbose_name='Просчеты отливов'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='other_complectation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.othercomplectation', verbose_name='Прочее комплектующие'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='price_constructor',
            field=models.FloatField(blank=True, default=0.0, max_length=255, null=True, verbose_name='Цена всего просчета'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.producttype', verbose_name='Тип изделия'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='sash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sash', verbose_name='Створка'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='sealant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealant', verbose_name='Уплотнитель'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='shtapik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.shtapik', verbose_name='Штапик'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='visors_calc',
            field=models.ManyToManyField(blank=True, to='calculation.visorscalc', verbose_name='Просчеты козырьков'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='window_calc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculation.windowscalc', verbose_name='Просчет окна'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='windowsills_calc',
            field=models.ManyToManyField(blank=True, to='calculation.windowsillcalc', verbose_name='Просчеты подоконников'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='works',
            field=models.ManyToManyField(blank=True, to='constructor.works', verbose_name='Работы'),
        ),
    ]
