# Generated by Django 4.1.2 on 2023-02-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0002_alter_visors_markups_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casingcalc',
            name='square_meter',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='В метрах квадратных'),
        ),
        migrations.AddField(
            model_name='visorscalc',
            name='square_meter',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='В метрах квадратных'),
        ),
    ]
