# Generated by Django 4.1.2 on 2022-10-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0002_rename_price_windowsillcalc_price_output'),
    ]

    operations = [
        migrations.CreateModel(
            name='Markups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windowsill', models.FloatField(default=0.0, max_length=255)),
            ],
        ),
    ]
