# Generated by Django 4.2 on 2023-05-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0002_rename_sploes_of_metal_calc_constructor_slopes_of_metal_calc'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='configuration',
            field=models.TextField(blank=True, null=True),
        ),
    ]
