# Generated by Django 4.1.2 on 2023-02-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0002_works_markups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='windowscalc',
            old_name='markup_name',
            new_name='markups_name',
        ),
        migrations.RenameField(
            model_name='windowscalc',
            old_name='markup_percent',
            new_name='markups_percent',
        ),
        migrations.RenameField(
            model_name='windowscalc',
            old_name='markup_type',
            new_name='markups_type',
        ),
        migrations.RenameField(
            model_name='windowscalc',
            old_name='markup_value',
            new_name='markups_value',
        ),
    ]
