# Generated by Django 4.1.2 on 2023-06-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0003_constructor_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
    ]
