# Generated by Django 4.1.2 on 2023-02-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0003_casingcalc_square_meter_visorscalc_square_meter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visorscalc',
            old_name='visor_id',
            new_name='visors_id',
        ),
    ]
