# Generated by Django 3.2 on 2022-10-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0003_alter_exchangerates_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowsillCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_windowsill', models.FloatField(default=0.0, max_length=255)),
                ('width', models.FloatField(default=0.0, max_length=255)),
                ('length', models.FloatField(default=0.0, max_length=255)),
                ('count', models.FloatField(default=0.0, max_length=255)),
                ('sum', models.FloatField(default=0, max_length=255)),
            ],
        ),
    ]
