# Generated by Django 4.1.2 on 2022-10-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0003_markups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='windowsillcalc',
            options={'verbose_name': 'Просчет подоконника', 'verbose_name_plural': 'Просчеты подоконников'},
        ),
        migrations.RenameField(
            model_name='windowsillcalc',
            old_name='windowsill_id',
            new_name='windowsill',
        ),
    ]
