# Generated by Django 4.1.2 on 2023-02-18 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0003_rename_markup_name_windowscalc_markups_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasingInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название монтажа')),
                ('value', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Стоимость монтажа')),
            ],
            options={
                'verbose_name': 'Монтаж наличников',
                'verbose_name_plural': 'Монтажи наличникв',
            },
        ),
        migrations.CreateModel(
            name='FlashingInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название монтажа')),
                ('value', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Стоимость монтажа')),
            ],
            options={
                'verbose_name': 'Монтаж нащельников',
                'verbose_name_plural': 'Монтажи нащельников',
            },
        ),
        migrations.CreateModel(
            name='InternalSlopeInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название монтажа')),
                ('value', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Стоимость монтажа')),
            ],
            options={
                'verbose_name': 'Монтаж внутренних откосов',
                'verbose_name_plural': 'Монтажи внутренних откосов',
            },
        ),
        migrations.CreateModel(
            name='LowTidesInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название монтажа')),
                ('value', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Стоимость монтажа')),
            ],
            options={
                'verbose_name': 'Монтаж отлива',
                'verbose_name_plural': 'Монтажи отливов',
            },
        ),
        migrations.CreateModel(
            name='MountingMaterialsCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mounting_materials_id', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='№ Монтажного материала')),
                ('markups_type', models.CharField(max_length=255, verbose_name='Наценка ')),
                ('count', models.FloatField(default=0.0, max_length=255, verbose_name='Количество')),
                ('price_output', models.FloatField(default=0.0, max_length=255, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Просчет внутреннего откоса ',
                'verbose_name_plural': 'Просчеты откосов из металла',
            },
        ),
        migrations.CreateModel(
            name='SlopesOfMetalInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название монтажа')),
                ('value', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Стоимость монтажа')),
            ],
            options={
                'verbose_name': 'Монтаж откосов из металла',
                'verbose_name_plural': 'Монтажи откосов из металла',
            },
        ),
        migrations.CreateModel(
            name='VisorsInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название монтажа')),
                ('value', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Стоимость монтажа')),
            ],
            options={
                'verbose_name': 'Монтаж козырька',
                'verbose_name_plural': 'Монтажи козырьков',
            },
        ),
        migrations.CreateModel(
            name='WindowsillInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название монтажа')),
                ('value', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Стоимость монтажа')),
            ],
            options={
                'verbose_name': 'Монтаж подоконников',
                'verbose_name_plural': 'Монтажи подоконников',
            },
        ),
        migrations.RenameField(
            model_name='works_markups',
            old_name='markup',
            new_name='markups',
        ),
        migrations.AddField(
            model_name='casingcalc',
            name='fastening',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Крепление'),
        ),
        migrations.AddField(
            model_name='lowtidescalc',
            name='plug',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Заглушка'),
        ),
        migrations.CreateModel(
            name='SlopesOfMetalCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slopes_of_metal_id', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='№ Откоса из металла')),
                ('markups_type', models.CharField(max_length=255, verbose_name='Наценка ')),
                ('width', models.FloatField(default=0.0, max_length=255, verbose_name='Ширина')),
                ('length', models.FloatField(default=0.0, max_length=255, verbose_name='Длинна')),
                ('count', models.FloatField(default=0.0, max_length=255, verbose_name='Количество')),
                ('linear_meter', models.FloatField(default=0.0, max_length=255, verbose_name='В метрах погонных')),
                ('square_meter', models.FloatField(default=0.0, max_length=255, verbose_name='В метрах квадратных')),
                ('price_output', models.FloatField(default=0.0, max_length=255, verbose_name='Цена')),
                ('installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculation.slopesofmetalinstallation', verbose_name='Установка')),
            ],
            options={
                'verbose_name': 'Просчет откосов из металла',
                'verbose_name_plural': 'Просчеты откосов из металла',
            },
        ),
        migrations.CreateModel(
            name='InternalSlopeCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_slope_id', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='№ Внутренние откосов')),
                ('markups_type', models.CharField(max_length=255, verbose_name='Наценка ')),
                ('width', models.FloatField(default=0.0, max_length=255, verbose_name='Ширина')),
                ('length', models.FloatField(default=0.0, max_length=255, verbose_name='Длинна')),
                ('count', models.FloatField(default=0.0, max_length=255, verbose_name='Количество')),
                ('linear_meter', models.FloatField(default=0.0, max_length=255, verbose_name='В метрах погонных')),
                ('square_meter', models.FloatField(default=0.0, max_length=255, verbose_name='В метрах квадратных')),
                ('price_output', models.FloatField(default=0.0, max_length=255, verbose_name='Цена')),
                ('installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculation.internalslopeinstallation', verbose_name='Установка')),
            ],
            options={
                'verbose_name': 'Просчет внутреннего откоса ',
                'verbose_name_plural': 'Просчеты откосов из металла',
            },
        ),
        migrations.AddField(
            model_name='casingcalc',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculation.casinginstallation', verbose_name='Установка'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='internal_slope_calc',
            field=models.ManyToManyField(blank=True, to='calculation.internalslopecalc', verbose_name='Просчеты внутренних откосов'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='mounting_materials_calc',
            field=models.ManyToManyField(blank=True, to='calculation.mountingmaterialscalc', verbose_name='Просчеты монтажные материалы'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='sploes_of_metal_calc',
            field=models.ManyToManyField(blank=True, to='calculation.slopesofmetalcalc', verbose_name='Просчеты откосов из металла'),
        ),
        migrations.AddField(
            model_name='flashingcalc',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculation.flashinginstallation', verbose_name='Установка'),
        ),
        migrations.AddField(
            model_name='lowtidescalc',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculation.lowtidesinstallation', verbose_name='Установка'),
        ),
        migrations.AddField(
            model_name='visorscalc',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculation.visorsinstallation', verbose_name='Установка'),
        ),
        migrations.AddField(
            model_name='windowsillcalc',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculation.windowsillinstallation', verbose_name='Установка'),
        ),
    ]
