# Generated by Django 4.1.2 on 2022-10-15 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0007_lowtidestype_lowtides_type'),
        ('calculation', '0004_alter_windowsillcalc_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='markups',
            options={'verbose_name': 'Наценки', 'verbose_name_plural': 'Наценки'},
        ),
        migrations.AddField(
            model_name='markups',
            name='low_tides',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='Отливы в %'),
        ),
        migrations.AlterField(
            model_name='markups',
            name='windowsill',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='Подоконники в %'),
        ),
        migrations.CreateModel(
            name='LowTidesCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(default=0.0, max_length=255)),
                ('length', models.FloatField(default=0.0, max_length=255)),
                ('count', models.FloatField(default=0.0, max_length=255)),
                ('price_output', models.FloatField(default=0.0, max_length=255)),
                ('low_tides', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.lowtides', verbose_name='Подоконник')),
            ],
            options={
                'verbose_name': 'Просчет подоконника',
                'verbose_name_plural': 'Просчеты подоконников',
            },
        ),
    ]
