# Generated by Django 4.1.2 on 2023-02-18 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0005_delete_accessories_delete_baywindowtoprofile60_and_more'),
        ('calculation', '0004_casinginstallation_flashinginstallation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Casing_Markups',
            new_name='CasingMarkups',
        ),
        migrations.RenameModel(
            old_name='Flashing_Markups',
            new_name='FlashingMarkups',
        ),
        migrations.RenameModel(
            old_name='LowTides_Markups',
            new_name='LowTidesMarkups',
        ),
        migrations.RenameModel(
            old_name='Visors_Markups',
            new_name='VisorsMarkups',
        ),
        migrations.RenameModel(
            old_name='Windowsill_Markups',
            new_name='WindowsillMarkups',
        ),
        migrations.CreateModel(
            name='SlopesOfMetalMarkups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markups_diler', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка диллерская')),
                ('markups_diler_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( диллер )')),
                ('markups_retail', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка розничная')),
                ('markups_retail_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( розница )')),
                ('markups_3', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка №3')),
                ('markups_3_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( наценка №3 )')),
                ('markups_4', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка №4')),
                ('markups_4_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( наценка №4 )')),
                ('markups_5', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка №5')),
                ('markups_5_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( наценка №5 )')),
                ('slopes_of_metal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.slopesofmetal', verbose_name='Откосы из металла')),
            ],
            options={
                'verbose_name': 'Наценка на откосы из металла',
                'verbose_name_plural': 'Наценка на откосы из металла',
            },
        ),
        migrations.CreateModel(
            name='InternalSlopeMarkups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markups_diler', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка диллерская')),
                ('markups_diler_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( диллер )')),
                ('markups_retail', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка розничная')),
                ('markups_retail_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( розница )')),
                ('markups_3', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка №3')),
                ('markups_3_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( наценка №3 )')),
                ('markups_4', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка №4')),
                ('markups_4_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( наценка №4 )')),
                ('markups_5', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка №5')),
                ('markups_5_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( наценка №5 )')),
                ('internal_slope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.internalslope', verbose_name='Внутренние откосы')),
            ],
            options={
                'verbose_name': 'Наценка на внутренние откосы',
                'verbose_name_plural': 'Наценка на внутренние откосы',
            },
        ),
    ]
