# Generated by Django 4.1.2 on 2023-06-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0004_constructor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='context',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контекст'),
        ),
    ]
