# Generated by Django 4.1.2 on 2023-01-21 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0005_article_articleadditionalprofile_colorinside_and_more'),
        ('calculation', '0004_remove_constructor_is_active_alter_constructor_door'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='other_complectation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.othercomplecation', verbose_name='Прочее комплектующие'),
        ),
    ]
