# Generated by Django 4.1.2 on 2023-06-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0005_constructor_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='final_image',
            field=models.ImageField(blank=True, null=True, upload_to='constructor_images/', verbose_name='Изображение'),
        ),
    ]
