# Generated by Django 4.1.2 on 2023-01-21 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0006_remove_sealant_execution_inside_and_more'),
        ('calculation', '0005_constructor_other_complectation'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='additional_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.additionalprofile', verbose_name='Доборные профиля'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='connection_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.connectionprofile', verbose_name='Соединительные профиля'),
        ),
    ]
