# Generated by Django 4.1.2 on 2023-08-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0005_casingcalc_nipel_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='slopesofmetalcalc',
            name='lock_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество замком'),
        ),
        migrations.AddField(
            model_name='slopesofmetalcalc',
            name='width_1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ширина 1'),
        ),
        migrations.AddField(
            model_name='slopesofmetalcalc',
            name='width_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ширина 2'),
        ),
        migrations.AddField(
            model_name='slopesofmetalcalc',
            name='width_3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ширина 3'),
        ),
        migrations.AddField(
            model_name='slopesofmetalcalc',
            name='width_4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ширина 4'),
        ),
        migrations.AlterField(
            model_name='slopesofmetalcalc',
            name='width',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ширина'),
        ),
    ]
