# Generated by Django 4.1.2 on 2022-10-15 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0008_alter_lowtides_options_lowtides_price_input_and_more'),
        ('calculation', '0005_alter_markups_options_markups_low_tides_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowtidescalc',
            name='low_tides',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.lowtides', verbose_name='Отлив'),
        ),
    ]
