# Generated by Django 4.1.2 on 2023-08-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0006_slopesofmetalcalc_lock_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalslopecalc',
            name='f_count',
            field=models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Кол-во F'),
        ),
        migrations.AddField(
            model_name='internalslopecalc',
            name='height_1',
            field=models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Высота 1'),
        ),
        migrations.AddField(
            model_name='internalslopecalc',
            name='height_2',
            field=models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Высота 2'),
        ),
        migrations.AddField(
            model_name='internalslopecalc',
            name='latch_count',
            field=models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Кол-во защелок'),
        ),
        migrations.AddField(
            model_name='internalslopecalc',
            name='lid_count',
            field=models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Кол-во крышек'),
        ),
        migrations.AddField(
            model_name='internalslopecalc',
            name='start_profile_length',
            field=models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Стартовый профиль в мп'),
        ),
        migrations.AlterField(
            model_name='internalslopecalc',
            name='length',
            field=models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Длинна'),
        ),
        migrations.AlterField(
            model_name='internalslopecalc',
            name='markups_type',
            field=models.CharField(max_length=255, verbose_name='Наценка'),
        ),
    ]
