# Generated by Django 4.1.2 on 2023-01-21 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0006_remove_sealant_execution_inside_and_more'),
        ('calculation', '0006_constructor_additional_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructor',
            name='door',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.door', verbose_name='Двери'),
        ),
    ]
