# Generated by Django 4.1.2 on 2023-06-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0006_constructor_final_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructor',
            name='final_image',
            field=models.TextField(blank=True, max_length=5000000, null=True, verbose_name='Изображение'),
        ),
    ]
