# Generated by Django 4.1.2 on 2022-10-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0006_alter_lowtidescalc_low_tides'),
    ]

    operations = [
        migrations.RenameField(
            model_name='windowdiscount',
            old_name='fitting_id',
            new_name='fittings_id',
        ),
    ]
