# Generated by Django 4.1.2 on 2023-08-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0007_internalslopecalc_f_count_internalslopecalc_height_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalslopecalc',
            name='casing_length',
            field=models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Наличник профиль в мп'),
        ),
    ]
