# Generated by Django 4.1.2 on 2023-01-31 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0007_alter_constructor_door'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowsillcalc',
            name='connector',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Соединитель'),
        ),
        migrations.AddField(
            model_name='windowsillcalc',
            name='linear_meter',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='В метрах погонных'),
        ),
        migrations.AddField(
            model_name='windowsillcalc',
            name='plug',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Заглушка'),
        ),
        migrations.AddField(
            model_name='windowsillcalc',
            name='square_meter',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='В метрах квадратных'),
        ),
        migrations.AlterField(
            model_name='windowsillcalc',
            name='count',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='windowsillcalc',
            name='length',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='Длинна'),
        ),
        migrations.AlterField(
            model_name='windowsillcalc',
            name='markups_type',
            field=models.CharField(max_length=255, verbose_name='Наценка'),
        ),
        migrations.AlterField(
            model_name='windowsillcalc',
            name='price_output',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='windowsillcalc',
            name='width',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='Ширина'),
        ),
    ]
