# Generated by Django 4.1.2 on 2022-10-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0007_rename_fitting_id_windowdiscount_fittings_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowtidescalc',
            name='low_tides',
            field=models.IntegerField(blank=True, default=0.0, null=True, verbose_name='№ Отлив'),
        ),
        migrations.AlterField(
            model_name='windowsillcalc',
            name='windowsill',
            field=models.IntegerField(blank=True, default=0.0, null=True, verbose_name='№ Подоконник'),
        ),
    ]
