# Generated by Django 4.1.2 on 2023-09-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0008_internalslopecalc_casing_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='slopesofmetalcalc',
            name='lock_width_1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Замок ширина 1'),
        ),
        migrations.AddField(
            model_name='slopesofmetalcalc',
            name='lock_width_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Замок ширина 2'),
        ),
        migrations.AddField(
            model_name='slopesofmetalcalc',
            name='lock_width_3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Замок ширина 3'),
        ),
        migrations.AddField(
            model_name='slopesofmetalcalc',
            name='lock_width_4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Замок ширина 4'),
        ),
        migrations.AddField(
            model_name='slopesofmetalcalc',
            name='low_tides_width_1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Отлив ширина 1'),
        ),
        migrations.AddField(
            model_name='slopesofmetalcalc',
            name='low_tides_width_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Отлив ширина 2'),
        ),
        migrations.AddField(
            model_name='slopesofmetalcalc',
            name='low_tides_width_3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Отлив ширина 3'),
        ),
        migrations.AddField(
            model_name='slopesofmetalcalc',
            name='low_tides_width_4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Отлив ширина 4'),
        ),
    ]
