# Generated by Django 4.1.2 on 2023-02-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0008_remove_casingcalc_installation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visorscalc',
            options={'verbose_name': 'Просчет козырька', 'verbose_name_plural': 'Просчеты козырьков'},
        ),
    ]
