# Generated by Django 4.1.2 on 2022-10-15 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0008_alter_lowtidescalc_low_tides_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lowtidescalc',
            old_name='low_tides',
            new_name='low_tides_id',
        ),
        migrations.RenameField(
            model_name='windowsillcalc',
            old_name='windowsill',
            new_name='windowsill_id',
        ),
    ]
