# Generated by Django 4.1.2 on 2023-01-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0008_windowsillcalc_connector_windowsillcalc_linear_meter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowtidescalc',
            name='linear_meter',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='В метрах погонных'),
        ),
        migrations.AddField(
            model_name='lowtidescalc',
            name='square_meter',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='В метрах квадратных'),
        ),
    ]
