# Generated by Django 4.1.2 on 2023-02-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0009_lowtidescalc_linear_meter_lowtidescalc_square_meter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasingCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casing_id', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='№ Наличник')),
                ('markups_type', models.CharField(max_length=255, verbose_name='Наценка ')),
                ('width', models.FloatField(default=0.0, max_length=255, verbose_name='Ширина')),
                ('length', models.FloatField(default=0.0, max_length=255, verbose_name='Длинна')),
                ('count', models.FloatField(default=0.0, max_length=255, verbose_name='Количество')),
                ('linear_meter', models.FloatField(default=0.0, max_length=255, verbose_name='В метрах погонных')),
                ('price_output', models.FloatField(default=0.0, max_length=255, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Просчет наличника',
                'verbose_name_plural': 'Просчеты наличников',
            },
        ),
        migrations.CreateModel(
            name='FlashingCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flashing_id', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='№ Нащельника')),
                ('markups_type', models.CharField(max_length=255, verbose_name='Наценка ')),
                ('width', models.FloatField(default=0.0, max_length=255, verbose_name='Ширина')),
                ('length', models.FloatField(default=0.0, max_length=255, verbose_name='Длинна')),
                ('count', models.FloatField(default=0.0, max_length=255, verbose_name='Количество')),
                ('linear_meter', models.FloatField(default=0.0, max_length=255, verbose_name='В метрах погонных')),
                ('price_output', models.FloatField(default=0.0, max_length=255, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Просчет нащельника',
                'verbose_name_plural': 'Просчеты нащельников',
            },
        ),
    ]
