# Generated by Django 4.1.2 on 2023-09-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0009_slopesofmetalcalc_lock_width_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slopesofmetalcalc',
            name='lock_width',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Замок ширина ( общая )'),
        ),
        migrations.AddField(
            model_name='slopesofmetalcalc',
            name='low_tides_width',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Отлив ширина ( общая ) '),
        ),
    ]
