# Generated by Django 4.1.2 on 2023-02-20 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0010_rename_fastening_casingcalc_fastening_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slopesofmetalcalc',
            name='fastening_id',
        ),
    ]
