# Generated by Django 4.1.2 on 2022-10-15 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0010_markups_window'),
    ]

    operations = [
        migrations.RenameField(
            model_name='windowdiscount',
            old_name='discount',
            new_name='value',
        ),
        migrations.CreateModel(
            name='WindowsCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_input', models.FloatField(default=0.0, max_length=255)),
                ('price_output', models.FloatField(default=0.0, max_length=255)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculation.exchangerates', verbose_name='Валюта')),
                ('discount_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculation.windowdiscount', verbose_name='Скидка на окно')),
            ],
            options={
                'verbose_name': 'Просчет окна',
                'verbose_name_plural': 'Просчеты окон',
            },
        ),
    ]
