# Generated by Django 4.1.2 on 2023-09-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0011_slopesofmetalcalc_lock_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slopesofmetalcalc',
            name='linear_meter_lock',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='В метрах погонных (замок)'),
        ),
        migrations.AddField(
            model_name='slopesofmetalcalc',
            name='linear_meter_low_tides',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='В метрах погонных (отлив)'),
        ),
        migrations.AddField(
            model_name='slopesofmetalcalc',
            name='square_meter_lock',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='В метрах квадратных (замок)'),
        ),
        migrations.AddField(
            model_name='slopesofmetalcalc',
            name='square_meter_low_tides',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='В метрах квадратных (отлив)'),
        ),
    ]
