# Generated by Django 4.1.2 on 2022-10-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0012_remove_windowscalc_discount_id_windowscalc_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowscalc',
            name='currency_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='windowscalc',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта значение'),
        ),
    ]
