# Generated by Django 4.1.2 on 2023-09-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0012_slopesofmetalcalc_linear_meter_lock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slopesofmetalcalc',
            name='price_lock',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='Цена замка'),
        ),
        migrations.AddField(
            model_name='slopesofmetalcalc',
            name='price_low_tides',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='Цена отлива'),
        ),
    ]
