# Generated by Django 4.1.2 on 2022-10-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0013_windowscalc_currency_name_alter_windowscalc_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windowscalc',
            name='currency',
        ),
        migrations.AddField(
            model_name='windowscalc',
            name='currency_value',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='Валюта значение'),
        ),
        migrations.AlterField(
            model_name='windowscalc',
            name='currency_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта имя'),
        ),
    ]
