# Generated by Django 4.1.2 on 2023-09-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0013_slopesofmetalcalc_price_lock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='stb_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='СТБ название'),
        ),
    ]
