# Generated by Django 4.1.2 on 2023-09-30 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0033_othercomplectationprofilearticle_and_more'),
        ('calculation', '0014_constructor_stb_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalProfileCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_profile_id', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='№ доборного профиля')),
                ('markups_type', models.CharField(max_length=255, verbose_name='Наценка ')),
                ('width', models.FloatField(default=0.0, max_length=255, verbose_name='Ширина')),
                ('length', models.FloatField(default=0.0, max_length=255, verbose_name='Длинна')),
                ('count', models.FloatField(default=0.0, max_length=255, verbose_name='Количество')),
                ('linear_meter', models.FloatField(default=0.0, max_length=255, verbose_name='В метрах погонных')),
                ('price_output', models.FloatField(default=0.0, max_length=255, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Просчет доборного профиля',
                'verbose_name_plural': 'Просчеты доборных профилей',
            },
        ),
        migrations.CreateModel(
            name='ConnectionProfileCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_profile_id', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='№ соединительного профиля')),
                ('markups_type', models.CharField(max_length=255, verbose_name='Наценка ')),
                ('width', models.FloatField(default=0.0, max_length=255, verbose_name='Ширина')),
                ('length', models.FloatField(default=0.0, max_length=255, verbose_name='Длинна')),
                ('count', models.FloatField(default=0.0, max_length=255, verbose_name='Количество')),
                ('linear_meter', models.FloatField(default=0.0, max_length=255, verbose_name='В метрах погонных')),
                ('price_output', models.FloatField(default=0.0, max_length=255, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Просчет соединительного профиля',
                'verbose_name_plural': 'Просчеты соединительных профилей',
            },
        ),
        migrations.CreateModel(
            name='OtherComplectationProfileCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_complectation_profile_id', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='№ Доп комп. профиля')),
                ('markups_type', models.CharField(max_length=255, verbose_name='Наценка ')),
                ('width', models.FloatField(default=0.0, max_length=255, verbose_name='Ширина')),
                ('length', models.FloatField(default=0.0, max_length=255, verbose_name='Длинна')),
                ('count', models.FloatField(default=0.0, max_length=255, verbose_name='Количество')),
                ('linear_meter', models.FloatField(default=0.0, max_length=255, verbose_name='В метрах погонных')),
                ('price_output', models.FloatField(default=0.0, max_length=255, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Просчет доп комп. профиля',
                'verbose_name_plural': 'Просчеты доп комп. профилей',
            },
        ),
        migrations.CreateModel(
            name='OtherComplectationProfileMarkups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markups_diler', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка диллерская')),
                ('markups_diler_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( диллер )')),
                ('markups_retail', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка розничная')),
                ('markups_retail_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( розница )')),
                ('markups_3', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка №3')),
                ('markups_3_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( наценка №3 )')),
                ('markups_4', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка №4')),
                ('markups_4_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( наценка №4 )')),
                ('markups_5', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка №5')),
                ('markups_5_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( наценка №5 )')),
                ('other_complectation_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.othercomplectationprofile', verbose_name='Доп комп. профиль')),
            ],
            options={
                'verbose_name': 'Наценка на доп комп. профиля',
                'verbose_name_plural': 'Наценка на доп комп. профиля',
            },
        ),
        migrations.CreateModel(
            name='ConnectionProfileMarkups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markups_diler', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка диллерская')),
                ('markups_diler_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( диллер )')),
                ('markups_retail', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка розничная')),
                ('markups_retail_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( розница )')),
                ('markups_3', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка №3')),
                ('markups_3_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( наценка №3 )')),
                ('markups_4', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка №4')),
                ('markups_4_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( наценка №4 )')),
                ('markups_5', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка №5')),
                ('markups_5_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( наценка №5 )')),
                ('connection_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.connectionprofile', verbose_name='Соединительные профиль')),
            ],
            options={
                'verbose_name': 'Наценка на соединительные профиля',
                'verbose_name_plural': 'Наценка на соединительные профиля',
            },
        ),
        migrations.CreateModel(
            name='AdditionalProfileMarkups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markups_diler', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка диллерская')),
                ('markups_diler_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( диллер )')),
                ('markups_retail', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка розничная')),
                ('markups_retail_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( розница )')),
                ('markups_3', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка №3')),
                ('markups_3_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( наценка №3 )')),
                ('markups_4', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка №4')),
                ('markups_4_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( наценка №4 )')),
                ('markups_5', models.FloatField(default=0.0, max_length=255, verbose_name='Наценка №5')),
                ('markups_5_in_percent', models.BooleanField(default=True, verbose_name='Добавлять в процентах ( наценка №5 )')),
                ('additional_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.additionalprofile', verbose_name='Доборный профиль')),
            ],
            options={
                'verbose_name': 'Наценка на доборные профиля',
                'verbose_name_plural': 'Наценка на доборные профиля',
            },
        ),
    ]
