# Generated by Django 4.1.2 on 2022-10-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0014_remove_windowscalc_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lowtidescalc',
            options={'verbose_name': 'Просчет отлива', 'verbose_name_plural': 'Просчеты отливов'},
        ),
        migrations.AlterField(
            model_name='exchangerates',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='exchangerates',
            name='value',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='lowtidescalc',
            name='count',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='lowtidescalc',
            name='length',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='длинна'),
        ),
        migrations.AlterField(
            model_name='lowtidescalc',
            name='price_output',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='lowtidescalc',
            name='width',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='ширина'),
        ),
        migrations.AlterField(
            model_name='windowdiscount',
            name='value',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='windowscalc',
            name='currency_value',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='Валюта значение НБРБ'),
        ),
        migrations.AlterField(
            model_name='windowscalc',
            name='price_input',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='Входная цена'),
        ),
        migrations.AlterField(
            model_name='windowscalc',
            name='price_output',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='Выходная цена ( с наценкой )'),
        ),
        migrations.AlterField(
            model_name='windowsillcalc',
            name='count',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='windowsillcalc',
            name='length',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='длинна'),
        ),
        migrations.AlterField(
            model_name='windowsillcalc',
            name='price_output',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='windowsillcalc',
            name='width',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='ширина'),
        ),
    ]
