# Generated by Django 4.1.2 on 2022-10-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0015_alter_lowtidescalc_options_alter_exchangerates_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowscalc',
            name='fittings_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Фурнитура id '),
        ),
        migrations.AddField(
            model_name='windowscalc',
            name='profile_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Профиль id'),
        ),
    ]
