# Generated by Django 4.1.2 on 2023-09-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0015_additionalprofilecalc_connectionprofilecalc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalprofilecalc',
            name='width',
        ),
    ]
