# Generated by Django 4.1.2 on 2023-09-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0016_remove_additionalprofilecalc_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectionprofilecalc',
            name='width',
        ),
        migrations.RemoveField(
            model_name='othercomplectationprofilecalc',
            name='width',
        ),
    ]
