# Generated by Django 4.1.2 on 2022-10-16 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0012_delete_constructor'),
        ('calculation', '0016_windowscalc_fittings_id_windowscalc_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('price_input', models.FloatField(blank=True, default=0.0, max_length=255, null=True, verbose_name='Входная цена')),
                ('currency', models.CharField(blank=True, default='RUS', max_length=255, null=True)),
                ('price_window', models.FloatField(blank=True, default=0.0, max_length=255, null=True, verbose_name='Цена окно ( с наценкой )')),
                ('price_works', models.FloatField(blank=True, default=0.0, max_length=255, null=True, verbose_name='Цена работы')),
                ('price_material', models.FloatField(blank=True, default=0.0, max_length=255, null=True, verbose_name='Цена материалов ( с наценкой )')),
                ('price_constructor', models.FloatField(blank=True, default=0.0, max_length=255, null=True, verbose_name='Цена всего просчета')),
                ('accessories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.accessories', verbose_name='Комлпектующие')),
                ('aggregate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.aggregate', verbose_name='Заполнитель №1')),
                ('bay_window_to_profile60', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.baywindowtoprofile60', verbose_name='Эркер к профилю 60мм')),
                ('bay_window_to_profile70', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.baywindowtoprofile70', verbose_name='Эркер к профилю 70мм')),
                ('connector_90g', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.connector90g', verbose_name='Соединитель 90гр')),
                ('extensions_to_profile60', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.extensionstoprofile60', verbose_name='Доборы к профилю 60мм')),
                ('extensions_to_profile70', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.extensionstoprofile70', verbose_name='Доборы к профилю 70мм')),
                ('favorite_positions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.favoritepositions', verbose_name='Избранные позиции')),
                ('fittings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.fittings', verbose_name='Фурнитура')),
                ('flashing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.flashing', verbose_name='Нащельник')),
                ('flashing_metal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.flashingmetal', verbose_name='Нащельник Металл')),
                ('free_positions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.freepositions', verbose_name='Бесплатные позиции')),
                ('handles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.handles', verbose_name='Ручка')),
                ('lamination_inside', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.laminationinside', verbose_name='Ланиманция внутри')),
                ('lamination_outside', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.laminationoutside', verbose_name='Ламинация снаружи')),
                ('locks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.locks', verbose_name='Замок')),
                ('lowtides', models.ManyToManyField(blank=True, null=True, to='calculation.lowtidescalc', verbose_name='Просчеты отливов')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.note', verbose_name='Примечание')),
                ('platband', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.platband', verbose_name='Наличник')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.producttype', verbose_name='Тип изделия')),
                ('products_install', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.productsinstall', verbose_name='Монтаж изделий')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.profile', verbose_name='Профиль')),
                ('profile_weight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.profileweight', verbose_name='Масса профиля')),
                ('pvc_slopes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.pvcslopes', verbose_name='Откосы ПВХ')),
                ('sash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sash', verbose_name='Створка')),
                ('seal_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealcolor', verbose_name='Цвет уплотнения')),
                ('seal_internal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealinternal', verbose_name='Уплотнение внутренее')),
                ('seal_outside', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealoutside', verbose_name='Уплотнение снаружи')),
                ('seal_rebate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealrebate', verbose_name='Уплотнение притвора')),
                ('shpros', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.shpros', verbose_name='Шпрос')),
                ('shtapik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.shtapik', verbose_name='Шталик')),
                ('straight_connectors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.straightconnectors', verbose_name='Прямые соединители')),
                ('supply_valve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.supplyvalve', verbose_name='Приточный клапан')),
                ('visors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.visors', verbose_name='Козырьки')),
                ('window_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculation.windowscalc', verbose_name='Просчет окна')),
                ('windowsill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.windowsill', verbose_name='Подоконники')),
                ('windowsills', models.ManyToManyField(blank=True, null=True, to='calculation.windowsillcalc', verbose_name='Просчеты подоконников')),
            ],
            options={
                'verbose_name': 'Просчет',
                'verbose_name_plural': 'Просчеты',
            },
        ),
    ]
