# Generated by Django 4.1.2 on 2022-10-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0017_constructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructor',
            name='lowtides',
            field=models.ManyToManyField(blank=True, to='calculation.lowtidescalc', verbose_name='Просчеты отливов'),
        ),
        migrations.AlterField(
            model_name='constructor',
            name='windowsills',
            field=models.ManyToManyField(blank=True, to='calculation.windowsillcalc', verbose_name='Просчеты подоконников'),
        ),
    ]
