# Generated by Django 4.1.2 on 2022-10-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0018_alter_constructor_lowtides_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructor',
            old_name='window_price',
            new_name='window_calc',
        ),
    ]
