# Generated by Django 4.1.2 on 2022-10-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0019_rename_window_price_constructor_window_calc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructor',
            options={'verbose_name': 'Просчет окна', 'verbose_name_plural': 'Просчеты окон'},
        ),
    ]
