# Generated by Django 4.1.2 on 2022-10-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0020_alter_constructor_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructor',
            old_name='lowtides',
            new_name='lowtides_calc',
        ),
        migrations.RenameField(
            model_name='constructor',
            old_name='windowsills',
            new_name='windowsills_calc',
        ),
        migrations.RemoveField(
            model_name='constructor',
            name='fittings',
        ),
        migrations.RemoveField(
            model_name='constructor',
            name='profile',
        ),
    ]
