# Generated by Django 4.1.2 on 2022-10-18 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0021_rename_lowtides_constructor_lowtides_calc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructor',
            name='currency',
        ),
    ]
