# Generated by Django 4.1.2 on 2022-10-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0022_remove_constructor_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта имя')),
                ('work_price', models.FloatField(default=0.0, max_length=255, verbose_name='Входная цена')),
            ],
            options={
                'verbose_name': 'Просчет работы',
                'verbose_name_plural': 'Просчеты работ',
            },
        ),
        migrations.AlterModelOptions(
            name='constructor',
            options={'verbose_name': 'Просчет конструктора', 'verbose_name_plural': 'Просчеты конструкторов'},
        ),
        migrations.RemoveField(
            model_name='constructor',
            name='price_works',
        ),
        migrations.AddField(
            model_name='constructor',
            name='price_works',
            field=models.ManyToManyField(blank=True, null=True, to='calculation.workcalc', verbose_name='Работы'),
        ),
    ]
