# Generated by Django 4.1.2 on 2022-10-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0023_workcalc_alter_constructor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcalc',
            name='work_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование работы'),
        ),
        migrations.AlterField(
            model_name='workcalc',
            name='work_price',
            field=models.FloatField(default=0.0, max_length=255, verbose_name='Цена работы'),
        ),
    ]
