# Generated by Django 4.1.2 on 2022-12-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.FileField(upload_to='IncomingMail/')),
            ],
            options={
                'verbose_name': 'Входящая корреспонденция',
                'verbose_name_plural': 'Входящая корреспонденция',
            },
        ),
        migrations.CreateModel(
            name='OutgoingMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.FileField(upload_to='OutgoingMail/')),
            ],
            options={
                'verbose_name': 'Исходящая корреспонденция',
                'verbose_name_plural': 'Исходящая корреспонденция',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
