# Generated by Django 4.1.2 on 2022-12-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0002_incomingmail_outgoingmail_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingmail',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='outgoingmail',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
