# Generated by Django 4.1.2 on 2023-02-06 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комлпектующие')),
            ],
            options={
                'verbose_name': 'Комлпектующие',
                'verbose_name_plural': 'Комлпектующие',
            },
        ),
        migrations.CreateModel(
            name='Aggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заполнитель №1')),
            ],
            options={
                'verbose_name': 'Заполнитель №1',
                'verbose_name_plural': 'Заполнитель №1',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Артикуль')),
            ],
            options={
                'verbose_name': 'Артикуль',
                'verbose_name_plural': 'Артикули',
            },
        ),
        migrations.CreateModel(
            name='ArticleAdditionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Артикуль')),
            ],
            options={
                'verbose_name': 'Артикуль доб. профиля',
                'verbose_name_plural': 'Артикуль доб. профиля',
            },
        ),
        migrations.CreateModel(
            name='BayWindowToProfile60',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Эркер к профилю 60мм')),
            ],
            options={
                'verbose_name': 'Эркер к профилю 60мм',
                'verbose_name_plural': 'Эркер к профилю 60мм',
            },
        ),
        migrations.CreateModel(
            name='BayWindowToProfile70',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Эркер к профилю 70мм')),
            ],
            options={
                'verbose_name': 'Эркер к профилю 70мм',
                'verbose_name_plural': 'Эркер к профилю 70мм',
            },
        ),
        migrations.CreateModel(
            name='Casing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название наличника')),
                ('price_input', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена закупки')),
            ],
            options={
                'verbose_name': 'Наличник',
                'verbose_name_plural': 'Наличники',
            },
        ),
        migrations.CreateModel(
            name='ColorInside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет внутри')),
            ],
            options={
                'verbose_name': 'Цвет внутри',
                'verbose_name_plural': 'Цвета внутри',
            },
        ),
        migrations.CreateModel(
            name='ColorOutside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет снаружи')),
            ],
            options={
                'verbose_name': 'Цвет снаружи',
                'verbose_name_plural': 'Цвета снаружи',
            },
        ),
        migrations.CreateModel(
            name='ConnectionProfileName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название соед.профиля')),
            ],
            options={
                'verbose_name': 'Название соед.профиля',
                'verbose_name_plural': 'Название соед.профиля',
            },
        ),
        migrations.CreateModel(
            name='Connector90g',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Соединитель 90гр')),
            ],
            options={
                'verbose_name': 'Соединитель 90гр',
                'verbose_name_plural': 'Соединитель 90гр',
            },
        ),
        migrations.CreateModel(
            name='Cylinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цилиндр')),
            ],
            options={
                'verbose_name': 'Цилиндр',
                'verbose_name_plural': 'Цилиндры',
            },
        ),
        migrations.CreateModel(
            name='DoorCloser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Доводчик')),
            ],
            options={
                'verbose_name': 'Доводчик',
                'verbose_name_plural': 'Доводчики',
            },
        ),
        migrations.CreateModel(
            name='DoorHandles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дверная ручки')),
            ],
            options={
                'verbose_name': 'Дверная ручка',
                'verbose_name_plural': 'Дверные ручки',
            },
        ),
        migrations.CreateModel(
            name='DoorHinges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дверные петли')),
            ],
            options={
                'verbose_name': 'Дверные петли',
                'verbose_name_plural': 'Дверные петли',
            },
        ),
        migrations.CreateModel(
            name='ExtensionsToProfile60',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Доборы к профилю 60мм')),
            ],
            options={
                'verbose_name': 'Доборы к профилю 60мм',
                'verbose_name_plural': 'Доборы к профилю 60мм',
            },
        ),
        migrations.CreateModel(
            name='ExtensionsToProfile70',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Доборы к профилю 70мм')),
            ],
            options={
                'verbose_name': 'Доборы к профилю 70мм',
                'verbose_name_plural': 'Доборы к профилю 70мм',
            },
        ),
        migrations.CreateModel(
            name='Fittings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фурнитура')),
            ],
            options={
                'verbose_name': 'Фурнитура',
                'verbose_name_plural': 'Фурнитуры',
            },
        ),
        migrations.CreateModel(
            name='Flashing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название нащельника')),
                ('price_input', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена закупки')),
            ],
            options={
                'verbose_name': 'Нащельник',
                'verbose_name_plural': 'Нащельники',
            },
        ),
        migrations.CreateModel(
            name='FlashingMetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Нащельник Металл')),
            ],
            options={
                'verbose_name': 'Нащельник Металл',
                'verbose_name_plural': 'Нащельник Металл',
            },
        ),
        migrations.CreateModel(
            name='FreePositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Бесплатные позиции')),
            ],
            options={
                'verbose_name': 'Бесплатные позиции',
                'verbose_name_plural': 'Бесплатные позиции',
            },
        ),
        migrations.CreateModel(
            name='Gorbylki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Горбыльки')),
            ],
            options={
                'verbose_name': 'Горбыльки',
                'verbose_name_plural': 'Горбыльки',
            },
        ),
        migrations.CreateModel(
            name='Handles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ручка')),
            ],
            options={
                'verbose_name': 'Ручка',
                'verbose_name_plural': 'Ручки',
            },
        ),
        migrations.CreateModel(
            name='LaminationInside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ланиманция внутри')),
            ],
            options={
                'verbose_name': 'Ланиманция внутри',
                'verbose_name_plural': 'Ланиманция внутри',
            },
        ),
        migrations.CreateModel(
            name='LaminationOutside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ламинация снаружи')),
            ],
            options={
                'verbose_name': 'Ламинация снаружи',
                'verbose_name_plural': 'Ламинация снаружи',
            },
        ),
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дверной замок')),
            ],
            options={
                'verbose_name': 'Дверной замок',
                'verbose_name_plural': 'Дверные замки',
            },
        ),
        migrations.CreateModel(
            name='Locks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Замок')),
            ],
            options={
                'verbose_name': 'Замок',
                'verbose_name_plural': 'Замки',
            },
        ),
        migrations.CreateModel(
            name='LowTides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название отлива')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип отлива')),
                ('price_input', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена закупки')),
            ],
            options={
                'verbose_name': 'Отлив',
                'verbose_name_plural': 'Отливы',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Примечание',
                'verbose_name_plural': 'Примечание',
            },
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Открывание')),
            ],
            options={
                'verbose_name': 'Открывание',
                'verbose_name_plural': 'Открывания',
            },
        ),
        migrations.CreateModel(
            name='OpeningLimiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ограничитель открывания')),
            ],
            options={
                'verbose_name': 'Ограничитель открывания',
                'verbose_name_plural': 'Ограничители открывания',
            },
        ),
        migrations.CreateModel(
            name='OtherComplectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Прочее комплектующие')),
            ],
            options={
                'verbose_name': 'Прочее комплектующие',
                'verbose_name_plural': 'Прочее комплектующие',
            },
        ),
        migrations.CreateModel(
            name='Platband',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наличник')),
            ],
            options={
                'verbose_name': 'Наличник',
                'verbose_name_plural': 'Наличник',
            },
        ),
        migrations.CreateModel(
            name='ProductsInstall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Монтаж изделий')),
            ],
            options={
                'verbose_name': 'Монтаж изделий',
                'verbose_name_plural': 'Монтаж изделий',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип изделия')),
            ],
            options={
                'verbose_name': 'Тип изделия',
                'verbose_name_plural': 'Тип изделия',
            },
        ),
        migrations.CreateModel(
            name='ProductTypeDoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип изделия')),
            ],
            options={
                'verbose_name': 'Тип изделия',
                'verbose_name_plural': 'Тип изделия',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='ProfileWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Масса профиля')),
            ],
            options={
                'verbose_name': 'Масса профиля',
                'verbose_name_plural': 'Масса профиля',
            },
        ),
        migrations.CreateModel(
            name='PvcSlopes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Откосы ПВХ')),
            ],
            options={
                'verbose_name': 'Откосы ПВХ',
                'verbose_name_plural': 'Откосы ПВХ',
            },
        ),
        migrations.CreateModel(
            name='Sash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Створка')),
            ],
            options={
                'verbose_name': 'Створка',
                'verbose_name_plural': 'Створки',
            },
        ),
        migrations.CreateModel(
            name='SealantColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет уплотнения')),
            ],
            options={
                'verbose_name': 'Цвет уплотнения',
                'verbose_name_plural': 'Цвет уплотнения',
            },
        ),
        migrations.CreateModel(
            name='SealantInside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Исполнение внутри')),
            ],
            options={
                'verbose_name': 'Исполнение внутри уплотнителя',
                'verbose_name_plural': 'Исполнение внутрии уплотнителя',
            },
        ),
        migrations.CreateModel(
            name='SealantOutside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Исполнение снаружи')),
            ],
            options={
                'verbose_name': 'Исполнение снаружи уплотнителя',
                'verbose_name_plural': 'Исполнение снаружи уплотнителя',
            },
        ),
        migrations.CreateModel(
            name='SealantShtapik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Штапик')),
            ],
            options={
                'verbose_name': 'Уплотнитель ( штапик )',
                'verbose_name_plural': 'Уплотнитель ( штапики )',
            },
        ),
        migrations.CreateModel(
            name='SealBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Исполнение основы детали')),
            ],
            options={
                'verbose_name': 'Исполнение основы детали',
                'verbose_name_plural': 'Исполнение основы детали',
            },
        ),
        migrations.CreateModel(
            name='SealInternal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Исполнение внутри')),
            ],
            options={
                'verbose_name': 'Исполнение внутри',
                'verbose_name_plural': 'Исполнение внутри',
            },
        ),
        migrations.CreateModel(
            name='SealOutside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Исполнение снаружи')),
            ],
            options={
                'verbose_name': 'Исполнение снаружи',
                'verbose_name_plural': 'Исполнение снаружи',
            },
        ),
        migrations.CreateModel(
            name='SealRebate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Уплотнение притвора')),
            ],
            options={
                'verbose_name': 'Уплотнение притвора',
                'verbose_name_plural': 'Уплотнение притвора',
            },
        ),
        migrations.CreateModel(
            name='Shpros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Шпрос')),
            ],
            options={
                'verbose_name': 'Шпрос',
                'verbose_name_plural': 'Шпросы',
            },
        ),
        migrations.CreateModel(
            name='Shtapik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Штапик')),
            ],
            options={
                'verbose_name': 'Штапик',
                'verbose_name_plural': 'Штапики',
            },
        ),
        migrations.CreateModel(
            name='StraightConnectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Прямые соединители')),
            ],
            options={
                'verbose_name': 'Прямые соединители',
                'verbose_name_plural': 'Прямые соединители',
            },
        ),
        migrations.CreateModel(
            name='SupplyValve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Приточный клапан')),
            ],
            options={
                'verbose_name': 'Приточный клапан',
                'verbose_name_plural': 'Приточные клапаны',
            },
        ),
        migrations.CreateModel(
            name='TypeLamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип ламинации')),
            ],
            options={
                'verbose_name': 'Тип ламинации',
                'verbose_name_plural': 'Типы ламинации',
            },
        ),
        migrations.CreateModel(
            name='TypeLamination2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид ламинации')),
            ],
            options={
                'verbose_name': 'Вид ламинации',
                'verbose_name_plural': 'Виды ламинации',
            },
        ),
        migrations.CreateModel(
            name='Visors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sweep', models.CharField(blank=True, max_length=255, null=True, verbose_name='Развертка')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Козырек')),
                ('price_input', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена закупки')),
            ],
            options={
                'verbose_name': 'Козырек',
                'verbose_name_plural': 'Козырьки',
            },
        ),
        migrations.CreateModel(
            name='Windowsill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название подоконника')),
                ('price_input', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена закупки')),
            ],
            options={
                'verbose_name': 'Подоконник',
                'verbose_name_plural': 'Подоконники',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование работы')),
                ('price', models.FloatField(default=0.0, max_length=255, verbose_name='Цена работы')),
            ],
            options={
                'verbose_name': 'Просчет работы',
                'verbose_name_plural': 'Просчеты работ',
            },
        ),
        migrations.CreateModel(
            name='Sealant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sealant_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealantcolor', verbose_name='Цвет уплотнителя')),
                ('sealant_inside', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealantinside', verbose_name='Исполнение снаружи')),
                ('sealant_outside', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealantoutside', verbose_name='Исполнение внутри')),
                ('sealant_shtapik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealantshtapik', verbose_name='Штапик')),
            ],
            options={
                'verbose_name': 'Уплотнитель',
                'verbose_name_plural': 'Уплотнители',
            },
        ),
        migrations.CreateModel(
            name='Lamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seal_basic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealbasic', verbose_name='Исполнение основы детали')),
                ('seal_internal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealinternal', verbose_name='Исполнение внутри')),
                ('seal_outside', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealoutside', verbose_name='Исполнение снаружи')),
                ('type_lamination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.typelamination', verbose_name='Тип ламинации')),
                ('type_lamination1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.typelamination2', verbose_name='Вид ламинации')),
            ],
            options={
                'verbose_name': 'Ламинация',
                'verbose_name_plural': 'Ламинации',
            },
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shtulp', models.BooleanField(blank=True, default=False, verbose_name='Со штульпом')),
                ('cylinder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.cylinder', verbose_name='Цилиндр')),
                ('door_closer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.doorcloser', verbose_name='Доводчик')),
                ('door_hinges', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.doorhinges', verbose_name='Дверные петли')),
                ('handle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.doorhandles', verbose_name='Дверные ручки')),
                ('lock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.lock', verbose_name='Замок')),
                ('opening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.opening', verbose_name='Открывание')),
                ('opening_limiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.openinglimiter', verbose_name='Ограничитель открывания')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.producttypedoor', verbose_name='Тип изделия')),
            ],
            options={
                'verbose_name': 'Дверь',
                'verbose_name_plural': 'Двери',
            },
        ),
        migrations.CreateModel(
            name='ConnectionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Длина')),
                ('price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.article', verbose_name='Артикуль')),
                ('color_inside', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.colorinside', verbose_name='Цвет внутри')),
                ('color_outside', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.coloroutside', verbose_name='Цвет снаружи')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.connectionprofilename', verbose_name='Название соен.профиля')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Соединительные профиля',
                'verbose_name_plural': 'Соединительные профиля',
            },
        ),
        migrations.CreateModel(
            name='AdditionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Ширина')),
                ('price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.articleadditionalprofile', verbose_name='Артикуль')),
            ],
            options={
                'verbose_name': 'Доборный профиль',
                'verbose_name_plural': 'Доборные профиля',
            },
        ),
    ]
