# Generated by Django 4.1.2 on 2023-02-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casing',
            name='provider',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='flashing',
            name='provider',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='lowtides',
            name='provider',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='profile',
            name='provider',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Прямой'), (1, 'Фигурный')], null=True, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='visors',
            name='provider',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='windowsill',
            name='provider',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Поставщик'),
        ),
    ]
