# Generated by Django 4.1.2 on 2023-06-08 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название поставщика')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Поставщик наличников',
                'verbose_name_plural': 'Поставщики наличников',
            },
        ),
        migrations.CreateModel(
            name='FlashingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название поставщика')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Поставщик нащельников',
                'verbose_name_plural': 'Поставщики нащельников',
            },
        ),
        migrations.CreateModel(
            name='InternalSlopeProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название поставщика')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Поставщик внутренние откосы',
                'verbose_name_plural': 'Поставщики внутренние откосы',
            },
        ),
        migrations.CreateModel(
            name='LowTidesProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название поставщика')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Поставщик отливов',
                'verbose_name_plural': 'Поставщики отливов',
            },
        ),
        migrations.CreateModel(
            name='MountingMaterialsProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название поставщика')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Поставщик материалов',
                'verbose_name_plural': 'Поставщики материалов',
            },
        ),
        migrations.CreateModel(
            name='ProviderWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Поставщик')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Поставщик профиля',
                'verbose_name_plural': 'Поставщики профилей',
            },
        ),
        migrations.CreateModel(
            name='SlopesOfMetalProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название поставщика')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Поставщик откосов из металла',
                'verbose_name_plural': 'Поставщики откосов из металла',
            },
        ),
        migrations.CreateModel(
            name='VisorsProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название поставщика')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Поставщик козырьков',
                'verbose_name_plural': 'Поставщики козырьков',
            },
        ),
        migrations.CreateModel(
            name='WindowsillProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название поставщика')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Поставщик подоконников',
                'verbose_name_plural': 'Поставщики подоконников',
            },
        ),
        migrations.DeleteModel(
            name='Locks',
        ),
        migrations.DeleteModel(
            name='StraightConnectors',
        ),
        migrations.DeleteModel(
            name='SupplyValve',
        ),
        migrations.AlterModelOptions(
            name='producttypedoor',
            options={'verbose_name': 'Тип изделия двери', 'verbose_name_plural': 'Тип изделия двери'},
        ),
        migrations.AlterModelOptions(
            name='works',
            options={'verbose_name': 'Работы', 'verbose_name_plural': 'Работы'},
        ),
        migrations.RenameField(
            model_name='additionalprofile',
            old_name='article',
            new_name='additional_article',
        ),
        migrations.RenameField(
            model_name='connectionprofile',
            old_name='article',
            new_name='connection_article',
        ),
        migrations.RemoveField(
            model_name='casing',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='flashing',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='internalslope',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='lowtides',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='mountingmaterialstype',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='slopesofmetal',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='visors',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='windowsill',
            name='provider',
        ),
        migrations.AddField(
            model_name='casing',
            name='casing_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.casingprovider', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='flashing',
            name='flashing_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.flashingprovider', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='internalslope',
            name='internal_slope_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.internalslopeprovider', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='lowtides',
            name='low_tides_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.lowtidesprovider', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='mountingmaterialstype',
            name='mounting_materials_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.mountingmaterialsprovider', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='profile',
            name='provider_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.providerwindow', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='slopesofmetal',
            name='slopes_of_metal_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.slopesofmetalprovider', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='visors',
            name='visors_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.visorsprovider', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='windowsill',
            name='windowsill_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.windowsillprovider', verbose_name='Поставщик'),
        ),
    ]
