# Generated by Django 4.1.2 on 2022-10-13 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WindowsillDankeKomfort',
        ),
        migrations.DeleteModel(
            name='WindowsillDankePremium',
        ),
        migrations.DeleteModel(
            name='WindowsillDankeStandart',
        ),
    ]
