# Generated by Django 4.1.2 on 2023-01-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип изделия')),
                ('shtulp', models.BooleanField(blank=True, default=False, verbose_name='Со штульпом')),
                ('opening', models.CharField(blank=True, max_length=255, verbose_name='Открывание')),
                ('lock', models.CharField(blank=True, max_length=255, verbose_name='Замок')),
                ('handle', models.CharField(blank=True, max_length=255, verbose_name='Ручка')),
                ('door_hinges', models.CharField(blank=True, max_length=255, verbose_name='Дверные петли')),
                ('cylinder', models.CharField(blank=True, max_length=255, verbose_name='Цилиндр')),
                ('door_closer', models.CharField(blank=True, max_length=255, verbose_name='Доводчик')),
                ('opening_limiter', models.CharField(blank=True, max_length=255, verbose_name='Ограничитель открывания')),
            ],
            options={
                'verbose_name': 'Дверь',
                'verbose_name_plural': 'Двери',
            },
        ),
        migrations.CreateModel(
            name='Lamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип ламинации')),
                ('type_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид ламинации')),
                ('seal_internal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Исполнение внутри')),
                ('seal_outside', models.CharField(blank=True, max_length=255, null=True, verbose_name='Исполнение снаружи')),
                ('seal_basic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Исполнение основы детали')),
            ],
            options={
                'verbose_name': 'Ламинация',
                'verbose_name_plural': 'Ламинации',
            },
        ),
        migrations.CreateModel(
            name='Sealant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет')),
                ('execution_outside', models.CharField(blank=True, max_length=255, null=True, verbose_name='Исполнение снаружи')),
                ('execution_inside', models.CharField(blank=True, max_length=255, null=True, verbose_name='Исполнение внутри')),
                ('shtapik', models.CharField(blank=True, max_length=255, null=True, verbose_name='Штапик')),
            ],
            options={
                'verbose_name': 'Уплотнитель',
                'verbose_name_plural': 'Уплотнители',
            },
        ),
    ]
