# Generated by Django 3.2 on 2022-09-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregate', models.CharField(blank=True, max_length=255, verbose_name='Заполнитель №1')),
            ],
        ),
        migrations.CreateModel(
            name='Fittings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fittings', models.CharField(blank=True, max_length=255, verbose_name='Фурнитура')),
            ],
        ),
        migrations.CreateModel(
            name='Free_positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_positions', models.CharField(blank=True, max_length=255, verbose_name='Бесплатные позиции')),
            ],
        ),
        migrations.CreateModel(
            name='Lamination_inside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lamination_inside', models.CharField(blank=True, max_length=255, verbose_name='Ланиманция внутри')),
            ],
        ),
        migrations.CreateModel(
            name='Lamination_outside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lamination_outside', models.CharField(blank=True, max_length=255, verbose_name='Ламинация снаружи')),
            ],
        ),
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_name', models.CharField(blank=True, max_length=255, verbose_name='Замок')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, verbose_name='Цена')),
                ('discount', models.FloatField(blank=True, verbose_name='Скидка')),
            ],
        ),
        migrations.CreateModel(
            name='Products_install',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_install', models.CharField(blank=True, max_length=255, verbose_name='Монтаж изделий')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type_name', models.CharField(blank=True, max_length=255, verbose_name='Тип изделия')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(blank=True, max_length=255, verbose_name='Профиль')),
                ('price', models.ManyToManyField(to='constructor.Price')),
            ],
        ),
        migrations.CreateModel(
            name='Profile_weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_weight', models.CharField(blank=True, max_length=255, verbose_name='Масса профиля')),
            ],
        ),
        migrations.CreateModel(
            name='Pvc_slopes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvc_slopes', models.CharField(blank=True, max_length=255, verbose_name='Откосы ПВХ')),
            ],
        ),
        migrations.CreateModel(
            name='Sash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sash', models.CharField(blank=True, max_length=255, verbose_name='Створка')),
            ],
        ),
        migrations.CreateModel(
            name='SealInternal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seal_internal', models.CharField(blank=True, max_length=255, verbose_name='Уплотнение внутренее')),
            ],
        ),
        migrations.CreateModel(
            name='SealOutside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seal_outside', models.CharField(blank=True, max_length=255, verbose_name='Уплотнение снаружи')),
            ],
        ),
        migrations.CreateModel(
            name='SealRebate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seal_rebate', models.CharField(blank=True, max_length=255, verbose_name='Уплотнение притвора')),
            ],
        ),
        migrations.CreateModel(
            name='Shpros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shpros_name', models.CharField(blank=True, max_length=255, verbose_name='Шпрос')),
            ],
        ),
        migrations.CreateModel(
            name='Shtapik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shtapik', models.CharField(blank=True, max_length=255, verbose_name='Шталик')),
            ],
        ),
        migrations.DeleteModel(
            name='Configuration',
        ),
        migrations.DeleteModel(
            name='ExtraMaterial',
        ),
        migrations.DeleteModel(
            name='ExtraWork',
        ),
        migrations.AddField(
            model_name='fittings',
            name='price',
            field=models.ManyToManyField(to='constructor.Price'),
        ),
    ]
