# Generated by Django 3.2 on 2022-09-27 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ручка')),
            ],
            options={
                'verbose_name': 'Ручка',
                'verbose_name_plural': 'Ручки',
            },
        ),
        migrations.CreateModel(
            name='Locks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Замок')),
            ],
            options={
                'verbose_name': 'Замок',
                'verbose_name_plural': 'Замки',
            },
        ),
        migrations.CreateModel(
            name='SealColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет уплотнения')),
            ],
            options={
                'verbose_name': 'Цвет уплотнения',
                'verbose_name_plural': 'Цвет уплотнения',
            },
        ),
        migrations.CreateModel(
            name='Supply_valve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Приточный клапан')),
            ],
            options={
                'verbose_name': 'Приточный клапан',
                'verbose_name_plural': 'Приточные клапаны',
            },
        ),
        migrations.RemoveField(
            model_name='constructor',
            name='handles_and_locks',
        ),
        migrations.AddField(
            model_name='constructor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.DeleteModel(
            name='Handles_and_locks',
        ),
        migrations.AddField(
            model_name='constructor',
            name='handles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.handles', verbose_name='Ручка'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='locks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.locks', verbose_name='Замок'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='seal_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealcolor', verbose_name='Цвет уплотнения'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='supply_valve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.supply_valve', verbose_name='Приточный клапан'),
        ),
    ]
