# Generated by Django 4.2 on 2023-05-01 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_provider_additionalprofile_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название поставщика')),
            ],
            options={
                'verbose_name': 'Поставщик наличников',
                'verbose_name_plural': 'Поставщики наличников',
            },
        ),
        migrations.CreateModel(
            name='FlashingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название поставщика')),
            ],
            options={
                'verbose_name': 'Поставщик нащельников',
                'verbose_name_plural': 'Поставщики нащельников',
            },
        ),
        migrations.CreateModel(
            name='InternalSlopeProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название поставщика')),
            ],
            options={
                'verbose_name': 'Поставщик внутренние откосы',
                'verbose_name_plural': 'Поставщики внутренние откосы',
            },
        ),
        migrations.CreateModel(
            name='LowTidesProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название поставщика')),
            ],
            options={
                'verbose_name': 'Поставщик отливов',
                'verbose_name_plural': 'Поставщики отливов',
            },
        ),
        migrations.CreateModel(
            name='MountingMaterialsProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название поставщика')),
            ],
            options={
                'verbose_name': 'Поставщик материалов',
                'verbose_name_plural': 'Поставщики материалов',
            },
        ),
        migrations.CreateModel(
            name='SlopesOfMetalProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название поставщика')),
            ],
            options={
                'verbose_name': 'Поставщик откосов из металла',
                'verbose_name_plural': 'Поставщики откосов из металла',
            },
        ),
        migrations.CreateModel(
            name='VisorsProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название поставщика')),
            ],
            options={
                'verbose_name': 'Поставщик козырьков',
                'verbose_name_plural': 'Поставщики козырьков',
            },
        ),
        migrations.CreateModel(
            name='WindowsillProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название поставщика')),
            ],
            options={
                'verbose_name': 'Поставщик подоконников',
                'verbose_name_plural': 'Поставщики подоконников',
            },
        ),
        migrations.RemoveField(
            model_name='casing',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='flashing',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='internalslope',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='lowtides',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='mountingmaterialstype',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='slopesofmetal',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='visors',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='windowsill',
            name='provider',
        ),
        migrations.AddField(
            model_name='casing',
            name='provider_casing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.casingprovider', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='flashing',
            name='provider_flashing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.flashingprovider', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='internalslope',
            name='provider_internal_slope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.internalslopeprovider', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='lowtides',
            name='provider_low_tides',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.lowtidesprovider', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='mountingmaterialstype',
            name='provider_mounting_materials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.mountingmaterialsprovider', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='slopesofmetal',
            name='provider_slopes_of_metal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.slopesofmetalprovider', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='visors',
            name='provider_visors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.visorsprovider', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='windowsill',
            name='provider_windowsill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.windowsillprovider', verbose_name='Поставщик'),
        ),
    ]
