# Generated by Django 3.2 on 2022-09-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_auto_20220920_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Цена', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AlterField(
            model_name='price',
            name='discount',
            field=models.IntegerField(blank=True, verbose_name='Скидка'),
        ),
    ]
