# Generated by Django 4.1.2 on 2023-01-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_door_lamination_sealant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gorbylki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Горбыльки')),
            ],
            options={
                'verbose_name': 'Горбыльки',
                'verbose_name_plural': 'Горбыльки',
            },
        ),
    ]
