# Generated by Django 4.1.2 on 2023-02-08 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_casing_provider_flashing_provider_lowtides_provider_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профиля'},
        ),
    ]
