# Generated by Django 3.2 on 2022-09-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_auto_20220927_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructor',
            name='lock',
        ),
        migrations.DeleteModel(
            name='Lock',
        ),
    ]
