# Generated by Django 3.2 on 2022-10-10 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0003_auto_20220927_1713'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bay_window_to_profile_sixty',
            new_name='BayWindowToProfile60',
        ),
        migrations.RenameModel(
            old_name='Bay_window_to_profile_seventy',
            new_name='BayWindowToProfile70',
        ),
        migrations.RenameModel(
            old_name='Connector_90g',
            new_name='Connector90g',
        ),
        migrations.RenameModel(
            old_name='Extensions_to_profile_sixty',
            new_name='ExtensionsToProfile60',
        ),
        migrations.RenameModel(
            old_name='Extensions_to_profile_seventy',
            new_name='ExtensionsToProfile70',
        ),
        migrations.RenameModel(
            old_name='Favorite_positions',
            new_name='FavoritePositions',
        ),
        migrations.RenameModel(
            old_name='Flashing_metal',
            new_name='FlashingMetal',
        ),
        migrations.RenameModel(
            old_name='Free_positions',
            new_name='FreePositions',
        ),
        migrations.RenameModel(
            old_name='Lamination_inside',
            new_name='LaminationInside',
        ),
        migrations.RenameModel(
            old_name='Lamination_outside',
            new_name='LaminationOutside',
        ),
        migrations.RenameModel(
            old_name='Low_tides',
            new_name='LowTides',
        ),
        migrations.RenameModel(
            old_name='Products_install',
            new_name='ProductsInstall',
        ),
        migrations.RenameModel(
            old_name='Profile_weight',
            new_name='ProfileWeight',
        ),
        migrations.RenameModel(
            old_name='Pvc_slopes',
            new_name='PvcSlopes',
        ),
        migrations.RenameModel(
            old_name='Straight_connectors',
            new_name='StraightConnectors',
        ),
        migrations.RenameModel(
            old_name='Supply_valve',
            new_name='SupplyValve',
        ),
        migrations.RenameModel(
            old_name='Windowsill_danke_komfort',
            new_name='WindowsillDankeKomfort',
        ),
        migrations.RenameModel(
            old_name='Windowsill_danke_premium',
            new_name='WindowsillDankePremium',
        ),
        migrations.RenameModel(
            old_name='Windowsill_danke_standart',
            new_name='WindowsillDankeStandart',
        ),
    ]
