# Generated by Django 4.1.2 on 2023-01-21 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0003_gorbylki'),
    ]

    operations = [
        migrations.CreateModel(
            name='SealBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Исполнение основы детали')),
            ],
            options={
                'verbose_name': 'Исполнение основы детали',
                'verbose_name_plural': 'Исполнение основы детали',
            },
        ),
        migrations.CreateModel(
            name='TypeLamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип ламинации')),
            ],
            options={
                'verbose_name': 'Тип ламинации',
                'verbose_name_plural': 'Типы ламинации',
            },
        ),
        migrations.CreateModel(
            name='TypeLamination2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид ламинации')),
            ],
            options={
                'verbose_name': 'Вид ламинации',
                'verbose_name_plural': 'Виды ламинации',
            },
        ),
        migrations.AlterModelOptions(
            name='sealinternal',
            options={'verbose_name': 'Исполнение внутри', 'verbose_name_plural': 'Исполнение внутри'},
        ),
        migrations.AlterModelOptions(
            name='sealoutside',
            options={'verbose_name': 'Исполнение снаружи', 'verbose_name_plural': 'Исполнение снаружи'},
        ),
        migrations.RemoveField(
            model_name='lamination',
            name='type',
        ),
        migrations.RemoveField(
            model_name='lamination',
            name='type_1',
        ),
        migrations.AlterField(
            model_name='lamination',
            name='seal_internal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealinternal', verbose_name='Исполнение внутри'),
        ),
        migrations.AlterField(
            model_name='lamination',
            name='seal_outside',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealoutside', verbose_name='Исполнение снаружи'),
        ),
        migrations.AlterField(
            model_name='sealinternal',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Исполнение внутри'),
        ),
        migrations.AlterField(
            model_name='sealoutside',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Исполнение снаружи'),
        ),
        migrations.AddField(
            model_name='lamination',
            name='type_lamination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.typelamination', verbose_name='Тип ламинации'),
        ),
        migrations.AddField(
            model_name='lamination',
            name='type_lamination1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.typelamination2', verbose_name='Вид ламинации'),
        ),
        migrations.AlterField(
            model_name='lamination',
            name='seal_basic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealbasic', verbose_name='Исполнение основы детали'),
        ),
    ]
