# Generated by Django 4.2 on 2023-05-01 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0003_casingprovider_flashingprovider_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provider',
            new_name='ProviderWindow',
        ),
        migrations.AlterModelOptions(
            name='providerwindow',
            options={'verbose_name': 'Поставщик профиля', 'verbose_name_plural': 'Поставщики профилей'},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='provider',
            new_name='provider_profile',
        ),
        migrations.RemoveField(
            model_name='additionalprofile',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='connectionprofile',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='othercomplectation',
            name='provider',
        ),
    ]
