# Generated by Django 3.2 on 2022-09-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0003_auto_20220920_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessories', models.CharField(blank=True, max_length=255, verbose_name='Комлпектующие')),
            ],
            options={
                'verbose_name': 'Комлпектующие',
                'verbose_name_plural': 'Комлпектующие',
            },
        ),
        migrations.CreateModel(
            name='Bay_window_to_profile_seventy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bay_window_to_profile_seventy', models.CharField(blank=True, max_length=255, verbose_name='Эркер к профилю 70мм')),
            ],
            options={
                'verbose_name': 'Эркер к профилю 70мм',
                'verbose_name_plural': 'Эркер к профилю 70мм',
            },
        ),
        migrations.CreateModel(
            name='Bay_window_to_profile_sixty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bay_window_to_profile_sixty', models.CharField(blank=True, max_length=255, verbose_name='Эркер к профилю 60мм')),
            ],
            options={
                'verbose_name': 'Эркер к профилю 60мм',
                'verbose_name_plural': 'Эркер к профилю 60мм',
            },
        ),
        migrations.CreateModel(
            name='Connector_90g',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_90g', models.CharField(blank=True, max_length=255, verbose_name='Соединитель 90гр')),
            ],
            options={
                'verbose_name': 'Соединитель 90гр',
                'verbose_name_plural': 'Соединитель 90гр',
            },
        ),
        migrations.CreateModel(
            name='Extensions_to_profile_seventy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extensions_to_profile_seventy', models.CharField(blank=True, max_length=255, verbose_name='Доборы к профилю 70мм')),
            ],
            options={
                'verbose_name': 'Доборы к профилю 70мм',
                'verbose_name_plural': 'Доборы к профилю 70мм',
            },
        ),
        migrations.CreateModel(
            name='Extensions_to_profile_sixty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extensions_to_profile_sixty', models.CharField(blank=True, max_length=255, verbose_name='Доборы к профилю 60мм')),
            ],
            options={
                'verbose_name': 'Доборы к профилю 60мм',
                'verbose_name_plural': 'Доборы к профилю 60мм',
            },
        ),
        migrations.CreateModel(
            name='Favorite_positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_positions', models.CharField(blank=True, max_length=255, verbose_name='Избранные позиции')),
            ],
            options={
                'verbose_name': 'Избранные позиции',
                'verbose_name_plural': 'Избранные позиции',
            },
        ),
        migrations.CreateModel(
            name='Flashing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flashing', models.CharField(blank=True, max_length=255, verbose_name='Нащельник')),
            ],
            options={
                'verbose_name': 'Нащельник',
                'verbose_name_plural': 'Нащельник',
            },
        ),
        migrations.CreateModel(
            name='Flashing_metal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flashing_metal', models.CharField(blank=True, max_length=255, verbose_name='Нащельник Металл')),
            ],
            options={
                'verbose_name': 'Нащельник Металл',
                'verbose_name_plural': 'Нащельник Металл',
            },
        ),
        migrations.CreateModel(
            name='Handles_and_locks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handles_and_locks', models.CharField(blank=True, max_length=255, verbose_name='Ручки и замки')),
            ],
            options={
                'verbose_name': 'Ручки и замки',
                'verbose_name_plural': 'Ручки и замки',
            },
        ),
        migrations.CreateModel(
            name='Low_tides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_tides', models.CharField(blank=True, max_length=255, verbose_name='Отливы')),
            ],
            options={
                'verbose_name': 'Отливы',
                'verbose_name_plural': 'Отливы',
            },
        ),
        migrations.CreateModel(
            name='Platband',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platband', models.CharField(blank=True, max_length=255, verbose_name='Наличник')),
            ],
            options={
                'verbose_name': 'Наличник',
                'verbose_name_plural': 'Наличник',
            },
        ),
        migrations.CreateModel(
            name='Straight_connectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('straight_connectors', models.CharField(blank=True, max_length=255, verbose_name='Прямые соединители')),
            ],
            options={
                'verbose_name': 'Прямые соединители',
                'verbose_name_plural': 'Прямые соединители',
            },
        ),
        migrations.CreateModel(
            name='Visors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visors', models.CharField(blank=True, max_length=255, verbose_name='Козырьки')),
            ],
            options={
                'verbose_name': 'Козырьки',
                'verbose_name_plural': 'Козырьки',
            },
        ),
        migrations.CreateModel(
            name='Windowsill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windowsill', models.CharField(blank=True, max_length=255, verbose_name='Подоконники')),
            ],
            options={
                'verbose_name': 'Подоконники',
                'verbose_name_plural': 'Подоконники',
            },
        ),
        migrations.CreateModel(
            name='Windowsill_danke_komfort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windowsill_danke_komfort', models.CharField(blank=True, max_length=255, verbose_name='Подоконник Danke Komfort')),
            ],
            options={
                'verbose_name': 'Подоконник Danke Komfort',
                'verbose_name_plural': 'Подоконник Danke Komfort',
            },
        ),
        migrations.CreateModel(
            name='Windowsill_danke_premium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windowsill_danke_premium', models.CharField(blank=True, max_length=255, verbose_name='Подоконник Danke Premium')),
            ],
            options={
                'verbose_name': 'Подоконник Danke Premium',
                'verbose_name_plural': 'Подоконник Danke Premium',
            },
        ),
        migrations.CreateModel(
            name='Windowsill_danke_standart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windowsill_danke_standart', models.CharField(blank=True, max_length=255, verbose_name='Подоконник Danke Standart')),
            ],
            options={
                'verbose_name': 'Подоконник Danke Standart',
                'verbose_name_plural': 'Подоконник Danke Standart',
            },
        ),
        migrations.AlterModelOptions(
            name='aggregate',
            options={'verbose_name': 'Заполнитель №1', 'verbose_name_plural': 'Заполнитель №1'},
        ),
        migrations.AlterModelOptions(
            name='fittings',
            options={'verbose_name': 'Фурнитура', 'verbose_name_plural': 'Фурнитуры'},
        ),
        migrations.AlterModelOptions(
            name='free_positions',
            options={'verbose_name': 'Бесплатные позиции', 'verbose_name_plural': 'Бесплатные позиции'},
        ),
        migrations.AlterModelOptions(
            name='lamination_inside',
            options={'verbose_name': 'Ланиманция внутри', 'verbose_name_plural': 'Ланиманция внутри'},
        ),
        migrations.AlterModelOptions(
            name='lamination_outside',
            options={'verbose_name': 'Ламинация снаружи', 'verbose_name_plural': 'Ламинация снаружи'},
        ),
        migrations.AlterModelOptions(
            name='lock',
            options={'verbose_name': 'Замок', 'verbose_name_plural': 'Замки'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Примечание', 'verbose_name_plural': 'Примечание'},
        ),
        migrations.AlterModelOptions(
            name='products_install',
            options={'verbose_name': 'Монтаж изделий', 'verbose_name_plural': 'Монтаж изделий'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Тип изделия', 'verbose_name_plural': 'Тип изделия'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='profile_weight',
            options={'verbose_name': 'Масса профиля', 'verbose_name_plural': 'Масса профиля'},
        ),
        migrations.AlterModelOptions(
            name='pvc_slopes',
            options={'verbose_name': 'Откосы ПВХ', 'verbose_name_plural': 'Откосы ПВХ'},
        ),
        migrations.AlterModelOptions(
            name='sash',
            options={'verbose_name': 'Створка', 'verbose_name_plural': 'Створки'},
        ),
        migrations.AlterModelOptions(
            name='sealinternal',
            options={'verbose_name': 'Уплотнение внутренее', 'verbose_name_plural': 'Уплотнение внутренее'},
        ),
        migrations.AlterModelOptions(
            name='sealoutside',
            options={'verbose_name': 'Уплотнение снаружи', 'verbose_name_plural': 'Уплотнение снаружи'},
        ),
        migrations.AlterModelOptions(
            name='sealrebate',
            options={'verbose_name': 'Уплотнение притвора', 'verbose_name_plural': 'Уплотнение притвора'},
        ),
        migrations.AlterModelOptions(
            name='shpros',
            options={'verbose_name': 'Шпрос', 'verbose_name_plural': 'Шпросы'},
        ),
        migrations.AlterModelOptions(
            name='shtapik',
            options={'verbose_name': 'Штапик', 'verbose_name_plural': 'Штапики'},
        ),
        migrations.AlterField(
            model_name='shtapik',
            name='shtapik',
            field=models.CharField(blank=True, max_length=255, verbose_name='Штапик'),
        ),
    ]
