# Generated by Django 4.1.2 on 2022-10-15 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0003_rename_price_constructor_price_input_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windowsill',
            name='price',
        ),
        migrations.AddField(
            model_name='windowsill',
            name='price_input',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена закупки'),
        ),
        migrations.AddField(
            model_name='windowsill',
            name='price_output',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена продажи'),
        ),
        migrations.AlterField(
            model_name='windowsill',
            name='color',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.windowsillcolor', verbose_name='Цвет подоконника'),
        ),
        migrations.AlterField(
            model_name='windowsill',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.windowsilltype', verbose_name='Тип подоконника'),
        ),
    ]
