# Generated by Django 4.2 on 2023-05-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0004_rename_provider_providerwindow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casingprovider',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='flashingprovider',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='internalslopeprovider',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='lowtidesprovider',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='mountingmaterialsprovider',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='slopesofmetalprovider',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='visorsprovider',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='windowsillprovider',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта'),
        ),
    ]
