# Generated by Django 4.1.2 on 2023-02-18 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0004_internalslope_mountingmaterials_slopesofmetal_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accessories',
        ),
        migrations.DeleteModel(
            name='BayWindowToProfile60',
        ),
        migrations.DeleteModel(
            name='BayWindowToProfile70',
        ),
        migrations.DeleteModel(
            name='Connector90g',
        ),
        migrations.DeleteModel(
            name='ExtensionsToProfile70',
        ),
    ]
