# Generated by Django 3.2 on 2022-10-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0004_auto_20221010_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructor',
            options={'verbose_name': 'Окно', 'verbose_name_plural': 'Окна'},
        ),
        migrations.AddField(
            model_name='fittings',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='profile',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='constructor',
            name='price',
            field=models.FloatField(default=0.0, max_length=255),
        ),
        migrations.RemoveField(
            model_name='fittings',
            name='price',
        ),
        migrations.AddField(
            model_name='fittings',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='price',
        ),
        migrations.AddField(
            model_name='profile',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
