# Generated by Django 4.1.2 on 2023-01-21 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0004_sealbasic_typelamination_typelamination2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Артикуль')),
            ],
            options={
                'verbose_name': 'Артикуль',
                'verbose_name_plural': 'Артикули',
            },
        ),
        migrations.CreateModel(
            name='ArticleAdditionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Артикуль')),
            ],
            options={
                'verbose_name': 'Артикуль доб. профиля',
                'verbose_name_plural': 'Артикуль доб. профиля',
            },
        ),
        migrations.CreateModel(
            name='ColorInside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет внутри')),
            ],
            options={
                'verbose_name': 'Цвет внутри',
                'verbose_name_plural': 'Цвета внутри',
            },
        ),
        migrations.CreateModel(
            name='ColorOutside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет снаружи')),
            ],
            options={
                'verbose_name': 'Цвет снаружи',
                'verbose_name_plural': 'Цвета снаружи',
            },
        ),
        migrations.CreateModel(
            name='ConnectionProfileName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название соед.профиля')),
            ],
            options={
                'verbose_name': 'Название соед.профиля',
                'verbose_name_plural': 'Название соед.профиля',
            },
        ),
        migrations.CreateModel(
            name='Cylinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цилиндр')),
            ],
            options={
                'verbose_name': 'Цилиндр',
                'verbose_name_plural': 'Цилиндры',
            },
        ),
        migrations.CreateModel(
            name='DoorCloser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Доводчик')),
            ],
            options={
                'verbose_name': 'Доводчик',
                'verbose_name_plural': 'Доводчики',
            },
        ),
        migrations.CreateModel(
            name='DoorHandles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дверная ручки')),
            ],
            options={
                'verbose_name': 'Дверная ручка',
                'verbose_name_plural': 'Дверные ручки',
            },
        ),
        migrations.CreateModel(
            name='DoorHinges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дверные петли')),
            ],
            options={
                'verbose_name': 'Дверные петли',
                'verbose_name_plural': 'Дверные петли',
            },
        ),
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дверной замок')),
            ],
            options={
                'verbose_name': 'Дверной замок',
                'verbose_name_plural': 'Дверные замки',
            },
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Открывание')),
            ],
            options={
                'verbose_name': 'Открывание',
                'verbose_name_plural': 'Открывания',
            },
        ),
        migrations.CreateModel(
            name='OpeningLimiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ограничитель открывания')),
            ],
            options={
                'verbose_name': 'Ограничитель открывания',
                'verbose_name_plural': 'Ограничители открывания',
            },
        ),
        migrations.CreateModel(
            name='OtherComplecation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Прочее комплектующие')),
            ],
            options={
                'verbose_name': 'Прочее комплектующие',
                'verbose_name_plural': 'Прочее комплектующие',
            },
        ),
        migrations.CreateModel(
            name='ProductTypeDoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип изделия')),
            ],
            options={
                'verbose_name': 'Тип изделия',
                'verbose_name_plural': 'Тип изделия',
            },
        ),
        migrations.CreateModel(
            name='SealantColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет уплотнителя')),
            ],
            options={
                'verbose_name': 'Цвет уплотнитель',
                'verbose_name_plural': 'Цвет уплотнители',
            },
        ),
        migrations.CreateModel(
            name='SealantInside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Исполнение внутри')),
            ],
            options={
                'verbose_name': 'Исполнение внутри уплотнителя',
                'verbose_name_plural': 'Исполнение внутрии уплотнителя',
            },
        ),
        migrations.CreateModel(
            name='SealantOutside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Исполнение снаружи')),
            ],
            options={
                'verbose_name': 'Исполнение снаружи уплотнителя',
                'verbose_name_plural': 'Исполнение снаружи уплотнителя',
            },
        ),
        migrations.CreateModel(
            name='SealantShtapik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Штапик')),
            ],
            options={
                'verbose_name': 'Уплотнитель ( штапик )',
                'verbose_name_plural': 'Уплотнитель ( штапики )',
            },
        ),
        migrations.CreateModel(
            name='ConnectionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Длина')),
                ('price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.article', verbose_name='Артикуль')),
                ('color_inside', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.colorinside', verbose_name='Цвет внутри')),
                ('color_outside', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.coloroutside', verbose_name='Цвет снаружи')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.connectionprofilename', verbose_name='Название соен.профиля')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Соединительные профиля',
                'verbose_name_plural': 'Соединительные профиля',
            },
        ),
        migrations.CreateModel(
            name='AdditionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Ширина')),
                ('price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.articleadditionalprofile', verbose_name='Артикуль')),
            ],
            options={
                'verbose_name': 'Соединительные профиля',
                'verbose_name_plural': 'Соединительные профиля',
            },
        ),
        migrations.AlterField(
            model_name='door',
            name='cylinder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.cylinder', verbose_name='Цилиндр'),
        ),
        migrations.AlterField(
            model_name='door',
            name='door_closer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.doorcloser', verbose_name='Доводчик'),
        ),
        migrations.AlterField(
            model_name='door',
            name='door_hinges',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.doorhinges', verbose_name='Дверные петли'),
        ),
        migrations.AlterField(
            model_name='door',
            name='handle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.doorhandles', verbose_name='Дверные ручки'),
        ),
        migrations.AlterField(
            model_name='door',
            name='lock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.lock', verbose_name='Открывание'),
        ),
        migrations.AlterField(
            model_name='door',
            name='opening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.opening', verbose_name='Открывание'),
        ),
        migrations.AlterField(
            model_name='door',
            name='opening_limiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.openinglimiter', verbose_name='Ограничитель открывания'),
        ),
        migrations.AlterField(
            model_name='door',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.producttypedoor', verbose_name='Тип изделия'),
        ),
    ]
