# Generated by Django 4.1.2 on 2022-10-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0004_remove_windowsill_price_windowsill_price_input_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='windowsill',
            options={'verbose_name': 'Подоконник', 'verbose_name_plural': 'Подоконники'},
        ),
        migrations.RemoveField(
            model_name='windowsill',
            name='name',
        ),
        migrations.RemoveField(
            model_name='windowsill',
            name='price_output',
        ),
    ]
