# Generated by Django 3.2 on 2022-10-11 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0005_auto_20221010_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fittings',
            name='discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Скидка'),
        ),
        migrations.CreateModel(
            name='DiscountWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField(default=0.0, max_length=255)),
                ('fittings_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.fittings', verbose_name='фурнитура')),
                ('profile_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Скидка на окно',
                'verbose_name_plural': 'Скидки на окна',
            },
        ),
    ]
