# Generated by Django 4.1.2 on 2023-02-20 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0005_delete_accessories_delete_baywindowtoprofile60_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowsillColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет подоконник',
                'verbose_name_plural': 'Цвет подоконников',
            },
        ),
        migrations.AlterField(
            model_name='windowsill',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.windowsillcolor', verbose_name='Цвет подоконника'),
        ),
    ]
