# Generated by Django 4.2 on 2023-05-01 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0005_casingprovider_currency_flashingprovider_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casing',
            old_name='provider_casing',
            new_name='casing_provider',
        ),
        migrations.RenameField(
            model_name='internalslope',
            old_name='provider_internal_slope',
            new_name='internal_slope_provider',
        ),
        migrations.RenameField(
            model_name='lowtides',
            old_name='provider_low_tides',
            new_name='low_tides_provider',
        ),
        migrations.RenameField(
            model_name='mountingmaterialstype',
            old_name='provider_mounting_materials',
            new_name='mounting_materials_provider',
        ),
        migrations.RenameField(
            model_name='slopesofmetal',
            old_name='provider_slopes_of_metal',
            new_name='slopes_of_metal_provider',
        ),
        migrations.RenameField(
            model_name='visors',
            old_name='provider_visors',
            new_name='visors_provider',
        ),
        migrations.RenameField(
            model_name='windowsill',
            old_name='provider_windowsill',
            new_name='windowsill_provider',
        ),
        migrations.RemoveField(
            model_name='flashing',
            name='provider_flashing',
        ),
        migrations.AddField(
            model_name='flashing',
            name='flashing_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.flashingprovider', verbose_name='Поставщик'),
        ),
    ]
