# Generated by Django 4.1.2 on 2023-01-21 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0005_article_articleadditionalprofile_colorinside_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sealant',
            name='execution_inside',
        ),
        migrations.RemoveField(
            model_name='sealant',
            name='execution_outside',
        ),
        migrations.RemoveField(
            model_name='sealant',
            name='shtapik',
        ),
        migrations.AddField(
            model_name='sealant',
            name='sealant_inside',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealantinside', verbose_name='Исполнение снаружи'),
        ),
        migrations.AddField(
            model_name='sealant',
            name='sealant_outside',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealantoutside', verbose_name='Исполнение внутри'),
        ),
        migrations.AddField(
            model_name='sealant',
            name='sealant_shtapik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealantshtapik', verbose_name='Штапик'),
        ),
        migrations.AlterField(
            model_name='sealant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealantcolor', verbose_name='Цвет'),
        ),
    ]
