# Generated by Django 4.1.2 on 2022-10-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0005_alter_windowsill_options_remove_windowsill_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowsilltype',
            name='type_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='windowsill_type'),
        ),
    ]
