# Generated by Django 3.2 on 2022-10-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0006_auto_20221011_2143'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiscountWindow',
            new_name='WindowDiscount',
        ),
    ]
