# Generated by Django 4.1.2 on 2022-10-15 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0006_windowsilltype_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowTidesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип отлива')),
            ],
            options={
                'verbose_name': 'Тип отлива',
                'verbose_name_plural': 'Типы отливов',
            },
        ),
        migrations.AddField(
            model_name='lowtides',
            name='type',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='constructor.lowtidestype', verbose_name='Тип отлива'),
            preserve_default=False,
        ),
    ]
