# Generated by Django 4.1.2 on 2023-01-21 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0007_alter_constructor_door'),
        ('constructor', '0006_remove_sealant_execution_inside_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtherComplecation',
            new_name='OtherComplectation',
        ),
        migrations.AlterField(
            model_name='door',
            name='lock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.lock', verbose_name='Замок'),
        ),
    ]
