# Generated by Django 4.1.2 on 2023-01-21 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0007_rename_othercomplecation_othercomplectation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SealColor',
        ),
        migrations.AlterModelOptions(
            name='sealantcolor',
            options={'verbose_name': 'Цвет уплотнения', 'verbose_name_plural': 'Цвет уплотнения'},
        ),
        migrations.RemoveField(
            model_name='sealant',
            name='color',
        ),
        migrations.AddField(
            model_name='sealant',
            name='sealant_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.sealantcolor', verbose_name='Цвет уплотнителя'),
        ),
        migrations.AlterField(
            model_name='sealantcolor',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет уплотнения'),
        ),
    ]
