# Generated by Django 3.2 on 2022-10-11 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0007_rename_discountwindow_windowdiscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fittings',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='fittings',
            name='price',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='price',
        ),
    ]
