# Generated by Django 4.1.2 on 2022-10-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0007_lowtidestype_lowtides_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lowtides',
            options={'verbose_name': 'Отлив', 'verbose_name_plural': 'Отливы'},
        ),
        migrations.AddField(
            model_name='lowtides',
            name='price_input',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена закупки'),
        ),
        migrations.AlterField(
            model_name='lowtides',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название отлива'),
        ),
    ]
