# Generated by Django 3.2 on 2022-10-11 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0008_auto_20221011_2219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WindowDiscount',
        ),
    ]
