# Generated by Django 4.1.2 on 2022-10-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0008_alter_lowtides_options_lowtides_price_input_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='price_constructor',
            field=models.FloatField(blank=True, default=0.0, max_length=255, null=True, verbose_name='Цена всего просчета'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='price_material',
            field=models.FloatField(blank=True, default=0.0, max_length=255, null=True, verbose_name='Цена материалов'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='price_window',
            field=models.FloatField(blank=True, default=0.0, max_length=255, null=True, verbose_name='Цена окно ( с наценкой )'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='price_works',
            field=models.FloatField(blank=True, default=0.0, max_length=255, null=True, verbose_name='Цена работы'),
        ),
    ]
