# Generated by Django 4.1.2 on 2023-01-22 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0008_delete_sealcolor_alter_sealantcolor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalprofile',
            options={'verbose_name': 'Доборный профиль', 'verbose_name_plural': 'Доборные профиля'},
        ),
    ]
