# Generated by Django 4.1.2 on 2023-02-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0008_windowsillcolor_windowsillinstallation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasingColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название цвета')),
            ],
            options={
                'verbose_name': 'Цвет наличника',
                'verbose_name_plural': 'Цвета наличников',
            },
        ),
        migrations.CreateModel(
            name='CasingInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название монтажа')),
                ('price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена монтажа')),
            ],
            options={
                'verbose_name': 'Монтаж наличника',
                'verbose_name_plural': 'Монтажи наличников',
            },
        ),
    ]
