# Generated by Django 4.1.2 on 2023-02-01 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0009_alter_additionalprofile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasingColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет наличника')),
            ],
            options={
                'verbose_name': 'Цвет наличника',
                'verbose_name_plural': 'Цвета наличников',
            },
        ),
        migrations.CreateModel(
            name='CasingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип наличника')),
            ],
            options={
                'verbose_name': 'Тип наличника',
                'verbose_name_plural': 'Типы наличников',
            },
        ),
        migrations.CreateModel(
            name='FlashingColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет нащельника')),
            ],
            options={
                'verbose_name': 'Цвет нащельника',
                'verbose_name_plural': 'Цвета нащельников',
            },
        ),
        migrations.CreateModel(
            name='FlashingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип нащельника')),
            ],
            options={
                'verbose_name': 'Тип нащельника',
                'verbose_name_plural': 'Типы нащельников',
            },
        ),
        migrations.CreateModel(
            name='VisorsColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет козырька')),
            ],
            options={
                'verbose_name': 'Цвет козырька',
                'verbose_name_plural': 'Цвета козырьков',
            },
        ),
        migrations.CreateModel(
            name='VisorsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип козырька')),
            ],
            options={
                'verbose_name': 'Тип козырька',
                'verbose_name_plural': 'Типы козырьков',
            },
        ),
        migrations.CreateModel(
            name='Casing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_input', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена закупки')),
                ('color', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.flashingcolor', verbose_name='Цвет наличников')),
                ('type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.flashingtype', verbose_name='Тип наличника')),
            ],
            options={
                'verbose_name': 'Наличник',
                'verbose_name_plural': 'Наличники',
            },
        ),
    ]
