# Generated by Django 3.2 on 2022-10-13 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0009_delete_windowdiscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowsillColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет подоконника')),
            ],
            options={
                'verbose_name': 'Цвет подоконника',
                'verbose_name_plural': 'Цвета подоконников',
            },
        ),
        migrations.AddField(
            model_name='windowsill',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='windowsilldankekomfort',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='windowsilldankepremium',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='windowsilldankestandart',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='constructor',
            name='price',
            field=models.FloatField(blank=True, default=0.0, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='windowsill',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='constructor.windowsillcolor'),
        ),
        migrations.AddField(
            model_name='windowsilldankekomfort',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='constructor.windowsillcolor'),
        ),
        migrations.AddField(
            model_name='windowsilldankepremium',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='constructor.windowsillcolor'),
        ),
        migrations.AddField(
            model_name='windowsilldankestandart',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='constructor.windowsillcolor'),
        ),
    ]
