# Generated by Django 4.1.2 on 2022-10-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0009_constructor_price_constructor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructor',
            name='price_output',
        ),
        migrations.AddField(
            model_name='constructor',
            name='currency',
            field=models.CharField(blank=True, default='RUS', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='constructor',
            name='price_input',
            field=models.FloatField(blank=True, default=0.0, max_length=255, null=True, verbose_name='Входная цена'),
        ),
        migrations.AlterField(
            model_name='constructor',
            name='price_material',
            field=models.FloatField(blank=True, default=0.0, max_length=255, null=True, verbose_name='Цена материалов ( с наценкой )'),
        ),
    ]
