# Generated by Django 4.1.2 on 2022-10-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0010_remove_constructor_price_output_constructor_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructor',
            options={'verbose_name': 'Просчет', 'verbose_name_plural': 'Просчеты'},
        ),
    ]
