# Generated by Django 3.2 on 2022-10-13 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0010_auto_20221013_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windowsill',
            name='color',
        ),
        migrations.RemoveField(
            model_name='windowsilldankekomfort',
            name='color',
        ),
        migrations.RemoveField(
            model_name='windowsilldankepremium',
            name='color',
        ),
        migrations.RemoveField(
            model_name='windowsilldankestandart',
            name='color',
        ),
        migrations.DeleteModel(
            name='WindowsillColor',
        ),
    ]
