# Generated by Django 4.1.2 on 2022-10-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0011_alter_constructor_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Constructor',
        ),
    ]
