# Generated by Django 4.1.2 on 2023-02-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0012_lowtidescolor_lowtidesinstallation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasingFastening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название крепление')),
            ],
            options={
                'verbose_name': 'Крепление наличника',
                'verbose_name_plural': 'Крепления наличников',
            },
        ),
    ]
