# Generated by Django 4.1.2 on 2023-02-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0013_casingfastening'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisorsColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название цвета')),
            ],
            options={
                'verbose_name': 'Цвет козырька',
                'verbose_name_plural': 'Цвета козырьков',
            },
        ),
        migrations.CreateModel(
            name='VisorsInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название монтажа')),
                ('price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена монтажа')),
            ],
            options={
                'verbose_name': 'Монтаж козырька',
                'verbose_name_plural': 'Монтажи козырьков',
            },
        ),
        migrations.AlterField(
            model_name='visors',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Развертка козырька'),
        ),
    ]
