# Generated by Django 4.1.2 on 2023-02-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0014_visorscolor_visorsinstallation_alter_visors_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlopesOfMetalColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название цвета')),
            ],
            options={
                'verbose_name': 'Цвет откосов из металла',
                'verbose_name_plural': 'Цвета откосов из металла',
            },
        ),
        migrations.CreateModel(
            name='SlopesOfMetalInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название монтажа')),
                ('price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена монтажа')),
            ],
            options={
                'verbose_name': 'Монтаж откосов из металла',
                'verbose_name_plural': 'Монтажи откосов из металла',
            },
        ),
    ]
