# Generated by Django 4.1.2 on 2023-02-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0015_slopesofmetalcolor_slopesofmetalinstallation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MountingMaterialsName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование монтажных материалов')),
            ],
            options={
                'verbose_name': 'Монтажные материалы',
                'verbose_name_plural': 'Монтажные материалы',
            },
        ),
        migrations.AlterModelOptions(
            name='mountingmaterials',
            options={'verbose_name': 'Тип монтажного материала', 'verbose_name_plural': 'Типы монтажных материалов'},
        ),
        migrations.RemoveField(
            model_name='mountingmaterials',
            name='name',
        ),
    ]
