# Generated by Django 4.1.2 on 2023-02-20 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0016_mountingmaterialsname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MountingMaterials',
            new_name='MountingMaterialsType',
        ),
    ]
