# Generated by Django 4.1.2 on 2023-08-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0018_slopesofmetallock_slopesofmetal_slopes_of_metal_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalslope',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Кюнель'), (1, 'ПВХ')], null=True, verbose_name='type'),
        ),
    ]
