# Generated by Django 4.1.2 on 2023-08-23 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0019_alter_internalslope_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalSlopeF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('price_input', models.FloatField(blank=True, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'F внутренние откосы',
                'verbose_name_plural': 'F внутренних откосов',
            },
        ),
        migrations.CreateModel(
            name='InternalSlopeLatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('price_input', models.FloatField(blank=True, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Защелка внутренние откосы',
                'verbose_name_plural': 'Защелки внутренних откосов',
            },
        ),
        migrations.CreateModel(
            name='InternalSlopeLid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('price_input', models.FloatField(blank=True, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Крышка внутренние откосы',
                'verbose_name_plural': 'Крышки внутренних откосов',
            },
        ),
        migrations.AddField(
            model_name='internalslope',
            name='internal_slope_f',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.internalslopef', verbose_name='F'),
        ),
        migrations.AddField(
            model_name='internalslope',
            name='internal_slope_latch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.internalslopelatch', verbose_name='Защелка'),
        ),
        migrations.AddField(
            model_name='internalslope',
            name='internal_slope_lid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.internalslopelid', verbose_name='Крышка'),
        ),
    ]
