# Generated by Django 4.1.2 on 2023-08-24 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0021_internalslopecasing_internalslopestartprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsternallSlopePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ширина')),
                ('price_input', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена закупки')),
                ('casing_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.internalslopeprovider', verbose_name='Поставщик')),
                ('internal_slope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.internalslope', verbose_name='Внутренние откосы')),
            ],
            options={
                'verbose_name': 'Цена на внутренние откосы',
                'verbose_name_plural': 'Цены на внутренние откосы',
            },
        ),
    ]
