# Generated by Django 4.1.2 on 2023-08-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0022_insternallslopeprice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InsternallSlopePrice',
            new_name='InsternalSlopePrice',
        ),
    ]
