# Generated by Django 4.1.2 on 2023-08-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0023_rename_insternallslopeprice_insternalslopeprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slopesofmetal',
            old_name='slopes_of_metal_provider',
            new_name='internal_slope_provider',
        ),
    ]
