# Generated by Django 4.1.2 on 2023-08-25 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0024_rename_slopes_of_metal_provider_slopesofmetal_internal_slope_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalslopeinstallation',
            name='internal_provider',
        ),
        migrations.AddField(
            model_name='internalslopecolor',
            name='internal_slope_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.internalslopeprovider', verbose_name='Поставщик'),
        ),
    ]
