# Generated by Django 4.1.2 on 2023-09-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0025_remove_internalslopeinstallation_internal_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casingprovider',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email контактного лица'),
        ),
        migrations.AddField(
            model_name='casingprovider',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='casingprovider',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон контактного лица'),
        ),
        migrations.AddField(
            model_name='casingprovider',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора'),
        ),
        migrations.AddField(
            model_name='casingprovider',
            name='contract_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия договора'),
        ),
        migrations.AddField(
            model_name='casingprovider',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='casingprovider',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='provider_documents/'),
        ),
        migrations.AddField(
            model_name='casingprovider',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Условия и положения'),
        ),
        migrations.AddField(
            model_name='flashingprovider',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email контактного лица'),
        ),
        migrations.AddField(
            model_name='flashingprovider',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='flashingprovider',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон контактного лица'),
        ),
        migrations.AddField(
            model_name='flashingprovider',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора'),
        ),
        migrations.AddField(
            model_name='flashingprovider',
            name='contract_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия договора'),
        ),
        migrations.AddField(
            model_name='flashingprovider',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='flashingprovider',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='provider_documents/'),
        ),
        migrations.AddField(
            model_name='flashingprovider',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Условия и положения'),
        ),
        migrations.AddField(
            model_name='internalslopeprovider',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email контактного лица'),
        ),
        migrations.AddField(
            model_name='internalslopeprovider',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='internalslopeprovider',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон контактного лица'),
        ),
        migrations.AddField(
            model_name='internalslopeprovider',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора'),
        ),
        migrations.AddField(
            model_name='internalslopeprovider',
            name='contract_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия договора'),
        ),
        migrations.AddField(
            model_name='internalslopeprovider',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='internalslopeprovider',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='provider_documents/'),
        ),
        migrations.AddField(
            model_name='internalslopeprovider',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Условия и положения'),
        ),
        migrations.AddField(
            model_name='lowtidesprovider',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email контактного лица'),
        ),
        migrations.AddField(
            model_name='lowtidesprovider',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='lowtidesprovider',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон контактного лица'),
        ),
        migrations.AddField(
            model_name='lowtidesprovider',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора'),
        ),
        migrations.AddField(
            model_name='lowtidesprovider',
            name='contract_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия договора'),
        ),
        migrations.AddField(
            model_name='lowtidesprovider',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='lowtidesprovider',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='provider_documents/'),
        ),
        migrations.AddField(
            model_name='lowtidesprovider',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Условия и положения'),
        ),
        migrations.AddField(
            model_name='mountingmaterialsprovider',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email контактного лица'),
        ),
        migrations.AddField(
            model_name='mountingmaterialsprovider',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='mountingmaterialsprovider',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон контактного лица'),
        ),
        migrations.AddField(
            model_name='mountingmaterialsprovider',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора'),
        ),
        migrations.AddField(
            model_name='mountingmaterialsprovider',
            name='contract_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия договора'),
        ),
        migrations.AddField(
            model_name='mountingmaterialsprovider',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='mountingmaterialsprovider',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='provider_documents/'),
        ),
        migrations.AddField(
            model_name='mountingmaterialsprovider',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Условия и положения'),
        ),
        migrations.AddField(
            model_name='providerwindow',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email контактного лица'),
        ),
        migrations.AddField(
            model_name='providerwindow',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='providerwindow',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон контактного лица'),
        ),
        migrations.AddField(
            model_name='providerwindow',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора'),
        ),
        migrations.AddField(
            model_name='providerwindow',
            name='contract_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия договора'),
        ),
        migrations.AddField(
            model_name='providerwindow',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='providerwindow',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='provider_documents/'),
        ),
        migrations.AddField(
            model_name='providerwindow',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Условия и положения'),
        ),
        migrations.AddField(
            model_name='slopesofmetalprovider',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email контактного лица'),
        ),
        migrations.AddField(
            model_name='slopesofmetalprovider',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='slopesofmetalprovider',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон контактного лица'),
        ),
        migrations.AddField(
            model_name='slopesofmetalprovider',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора'),
        ),
        migrations.AddField(
            model_name='slopesofmetalprovider',
            name='contract_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия договора'),
        ),
        migrations.AddField(
            model_name='slopesofmetalprovider',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='slopesofmetalprovider',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='provider_documents/'),
        ),
        migrations.AddField(
            model_name='slopesofmetalprovider',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Условия и положения'),
        ),
        migrations.AddField(
            model_name='visorsprovider',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email контактного лица'),
        ),
        migrations.AddField(
            model_name='visorsprovider',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='visorsprovider',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон контактного лица'),
        ),
        migrations.AddField(
            model_name='visorsprovider',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора'),
        ),
        migrations.AddField(
            model_name='visorsprovider',
            name='contract_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия договора'),
        ),
        migrations.AddField(
            model_name='visorsprovider',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='visorsprovider',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='provider_documents/'),
        ),
        migrations.AddField(
            model_name='visorsprovider',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Условия и положения'),
        ),
        migrations.AddField(
            model_name='windowsillcolorprovider',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email контактного лица'),
        ),
        migrations.AddField(
            model_name='windowsillcolorprovider',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='windowsillcolorprovider',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон контактного лица'),
        ),
        migrations.AddField(
            model_name='windowsillcolorprovider',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора'),
        ),
        migrations.AddField(
            model_name='windowsillcolorprovider',
            name='contract_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия договора'),
        ),
        migrations.AddField(
            model_name='windowsillcolorprovider',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='windowsillcolorprovider',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='provider_documents/'),
        ),
        migrations.AddField(
            model_name='windowsillcolorprovider',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Условия и положения'),
        ),
        migrations.AddField(
            model_name='windowsillprovider',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email контактного лица'),
        ),
        migrations.AddField(
            model_name='windowsillprovider',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='windowsillprovider',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон контактного лица'),
        ),
        migrations.AddField(
            model_name='windowsillprovider',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора'),
        ),
        migrations.AddField(
            model_name='windowsillprovider',
            name='contract_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия договора'),
        ),
        migrations.AddField(
            model_name='windowsillprovider',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='windowsillprovider',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='provider_documents/'),
        ),
        migrations.AddField(
            model_name='windowsillprovider',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Условия и положения'),
        ),
    ]
