# Generated by Django 4.1.2 on 2023-09-10 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0026_casingprovider_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slopesofmetal',
            old_name='internal_slope_provider',
            new_name='slopes_of_metal_provider',
        ),
    ]
