# Generated by Django 4.1.2 on 2023-09-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0029_slopesofmetallowtides_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slopesofmetallowtides',
            options={'verbose_name': 'Отлив откосов из металла', 'verbose_name_plural': 'Отливы откосов из металла'},
        ),
        migrations.AlterField(
            model_name='slopesofmetallowtides',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название отлива'),
        ),
        migrations.AlterField(
            model_name='slopesofmetallowtides',
            name='price_input',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена отлива'),
        ),
    ]
