# Generated by Django 4.1.2 on 2023-09-29 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0030_alter_slopesofmetallowtides_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalProfileWidth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ширина')),
            ],
            options={
                'verbose_name': 'Ширина доб. профиля',
                'verbose_name_plural': 'Ширина доб. профиля',
            },
        ),
        migrations.CreateModel(
            name='AdditionalProfileWidth1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ширина')),
            ],
            options={
                'verbose_name': 'Ширина 2 доб. профиля',
                'verbose_name_plural': 'Ширина 2 доб. профиля',
            },
        ),
        migrations.RemoveField(
            model_name='additionalprofile',
            name='price',
        ),
        migrations.RemoveField(
            model_name='additionalprofile',
            name='width',
        ),
        migrations.AddField(
            model_name='additionalprofile',
            name='additional_lamination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.additionalprofilelamination', verbose_name='Ламинация'),
        ),
        migrations.AlterField(
            model_name='additionalprofile',
            name='additional_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.articleadditionalprofile', verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='additionalprofile',
            name='additional_width',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.additionalprofilewidth', verbose_name='Ширина 1'),
        ),
        migrations.AddField(
            model_name='additionalprofile',
            name='additional_width1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.additionalprofilewidth1', verbose_name='Ширина 2'),
        ),
    ]
