# Generated by Django 4.1.2 on 2023-09-30 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0031_additionalprofilewidth_additionalprofilewidth1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionProfileArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Артикулы соединительных профилей',
                'verbose_name_plural': 'Артикулы соединительных профилей',
            },
        ),
        migrations.CreateModel(
            name='ConnectionProfileLamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Ламинация соединительных профилей',
                'verbose_name_plural': 'Ламинация соединительных профилей',
            },
        ),
        migrations.CreateModel(
            name='ConnectionProfileWidth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Ширина 1 соединительных профилей',
                'verbose_name_plural': 'Ширина 1 соединительных профилей',
            },
        ),
        migrations.CreateModel(
            name='ConnectionProfileWidth1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Ширина 2 соединительных профилей',
                'verbose_name_plural': 'Ширина 2 соединительных профилей',
            },
        ),
        migrations.AlterModelOptions(
            name='connectionprofile',
            options={'verbose_name': 'Соединительные профиль', 'verbose_name_plural': 'Соединительные профиля'},
        ),
        migrations.RemoveField(
            model_name='connectionprofile',
            name='color_inside',
        ),
        migrations.RemoveField(
            model_name='connectionprofile',
            name='color_outside',
        ),
        migrations.RemoveField(
            model_name='connectionprofile',
            name='length',
        ),
        migrations.RemoveField(
            model_name='connectionprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='connectionprofile',
            name='price',
        ),
        migrations.RemoveField(
            model_name='connectionprofile',
            name='profile',
        ),
        migrations.AddField(
            model_name='additionalprofile',
            name='price_input',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена BYN'),
        ),
        migrations.AddField(
            model_name='connectionprofile',
            name='price_input',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена BYN'),
        ),
        migrations.AddField(
            model_name='connectionprofile',
            name='connection_lamination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.connectionprofilelamination', verbose_name='Ламинация'),
        ),
        migrations.AddField(
            model_name='connectionprofile',
            name='connection_width',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.connectionprofilewidth', verbose_name='Ширина 1'),
        ),
        migrations.AddField(
            model_name='connectionprofile',
            name='connection_width1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.connectionprofilewidth1', verbose_name='Ширина 2'),
        ),
        migrations.AlterField(
            model_name='connectionprofile',
            name='connection_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.connectionprofilearticle', verbose_name='Артикул'),
        ),
    ]
