# Generated by Django 4.1.2 on 2023-09-30 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0032_connectionprofilearticle_connectionprofilelamination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherComplectationProfileArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Артикул')),
            ],
            options={
                'verbose_name': 'Доп. комп. артикулы',
                'verbose_name_plural': 'Доп. комп. артикулы ',
            },
        ),
        migrations.CreateModel(
            name='OtherComplectationProfileLamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ламинация')),
            ],
            options={
                'verbose_name': 'Доп. комп ламинация',
                'verbose_name_plural': 'Доп. комп. ламинация',
            },
        ),
        migrations.CreateModel(
            name='OtherComplectationProfileWidth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ширина')),
            ],
            options={
                'verbose_name': 'Доп. комп ширина 1',
                'verbose_name_plural': 'Доп. комп. ширина 1',
            },
        ),
        migrations.CreateModel(
            name='OtherComplectationProfileWidth1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ширина')),
            ],
            options={
                'verbose_name': 'Доп. комп ширина 2',
                'verbose_name_plural': 'Доп. комп. ширина 2',
            },
        ),
        migrations.CreateModel(
            name='OtherComplectationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_input', models.FloatField(blank=True, null=True, verbose_name='Цена BYN')),
                ('additional_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.othercomplectationprofilearticle', verbose_name='Артикул')),
                ('additional_lamination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.othercomplectationprofilelamination', verbose_name='Ламинация')),
                ('additional_width', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.othercomplectationprofilewidth', verbose_name='Ширина 1')),
                ('additional_width1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.othercomplectationprofilewidth1', verbose_name='Ширина 2')),
            ],
            options={
                'verbose_name': 'Доп. компл. профиль',
                'verbose_name_plural': 'Доп компл. профиля',
            },
        ),
    ]
