# Generated by Django 4.1.2 on 2023-10-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0033_othercomplectationprofilearticle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование'),
        ),
    ]
