# Generated by Django 4.1.2 on 2023-10-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0034_additionalprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование'),
        ),
    ]
