# Generated by Django 4.1.2 on 2023-10-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0035_connectionprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='othercomplectationprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование'),
        ),
    ]
