# Generated by Django 4.1.2 on 2022-12-12 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('call', '0002_remove_call_client_name_alter_call_client_id'),
        ('client', '0002_client_complaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call.call')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
    ]
