# Generated by Django 4.1.2 on 2022-12-12 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0002_remove_call_client_name_alter_call_client_id'),
        ('client', '0002_client_complaints'),
        ('calls_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callstable',
            name='call',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='call.call'),
        ),
        migrations.AlterField(
            model_name='callstable',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
