# Generated by Django 4.1.2 on 2022-12-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls_table', '0002_alter_callstable_call_alter_callstable_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callstable',
            options={'ordering': ['id']},
        ),
    ]
