# Generated by Django 4.1.2 on 2023-02-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls_table', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingCalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
