# Generated by Django 4.1.2 on 2022-12-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls_table', '0003_alter_callstable_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callstable',
            options={},
        ),
    ]
