# Generated by Django 4.1.2 on 2023-02-10 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls_table', '0004_rename_number_outgoingcalls_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outgoingcalls',
            old_name='number_phone',
            new_name='number',
        ),
    ]
