# Generated by Django 4.1.2 on 2023-02-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls_table', '0005_rename_number_phone_outgoingcalls_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OutgoingCalls',
        ),
    ]
